import type { PythonCheatItem } from "./pythonCheatsheet";

export const pythonDesignCheatsheet: PythonCheatItem[] = [
  {
    id: "design-exception-hierarchy", category: "Engineering Design", title: "Exception hierarchy", action: "为模块设计稳定的错误分类",
    description: "公开一个模块基础异常，再按调用方真正需要的处理策略细分；不要镜像每个内部失败。",
    syntax: "AppError -> ValidationError / ConflictError / ExternalServiceError",
    code: "class ApplicationError(Exception):\n    \"\"\"Base error callers may safely catch.\"\"\"\n\nclass ValidationError(ApplicationError):\n    pass\n\nclass ConflictError(ApplicationError):\n    pass\n\ndef submit(company: str) -> None:\n    if not company.strip():\n        raise ValidationError(\"company is required\")",
    aliases: ["exception hierarchy", "domain errors", "error taxonomy", "异常层级", "错误分类"],
    whenToUse: "库或业务模块需要让上层稳定地决定重试、提示用户或返回 HTTP 状态。",
    commonMistake: "为每个函数创建一种异常，调用方只能 catch 十几个无意义的类型。",
  },
  {
    id: "design-value-object", category: "Engineering Design", title: "Immutable value object", action: "用不可变对象表达有规则的值",
    description: "value object 由内容决定相等性，并在创建时保证自身永远有效。",
    syntax: "@dataclass(frozen=True, slots=True)",
    code: "from dataclasses import dataclass\n\n@dataclass(frozen=True, slots=True)\nclass Email:\n    value: str\n\n    def __post_init__(self):\n        normalized = self.value.strip().lower()\n        if \"@\" not in normalized:\n            raise ValueError(\"invalid email\")\n        object.__setattr__(self, \"value\", normalized)\n\nemail = Email(\"Bruce@Example.com\")",
    aliases: ["value object", "immutable dataclass", "frozen dataclass", "值对象", "不可变对象"],
    whenToUse: "Email、Money、DateRange 等带不变量、会跨多层传递的领域值。",
    commonMistake: "把只有一个字段且没有规则的所有值都包装成类，增加无意义 ceremony。",
  },
  {
    id: "design-repository", category: "Engineering Design", title: "Repository pattern", action: "用领域接口隔离持久化细节",
    description: "repository 提供业务需要的集合式操作，不泄露 SQLAlchemy Query、HTTP response 等基础设施类型。",
    syntax: "Protocol Repository: get/save/list_matching",
    code: "from typing import Protocol\n\nclass JobRepository(Protocol):\n    def get(self, job_id: str) -> dict | None: ...\n    def save(self, job: dict) -> None: ...\n\nclass InMemoryJobs:\n    def __init__(self):\n        self.items = {}\n    def get(self, job_id):\n        return self.items.get(job_id)\n    def save(self, job):\n        self.items[job[\"id\"]] = job",
    aliases: ["repository pattern", "data access abstraction", "persistence port", "仓储模式", "数据访问层"],
    whenToUse: "业务规则需要独立于数据库测试，或存在多个数据来源。",
    commonMistake: "创建只把 ORM 每个方法原样转发一遍的 repository，没有形成业务语言。",
  },
  {
    id: "design-service-layer", category: "Engineering Design", title: "Service layer / use case", action: "把业务流程组织成明确用例",
    description: "service 协调领域对象、repository 和外部端口；入口对应用户可理解的动作。",
    syntax: "service.execute(command) -> result",
    code: "class ApplyToJob:\n    def __init__(self, jobs, applications, clock):\n        self.jobs = jobs\n        self.applications = applications\n        self.clock = clock\n\n    def execute(self, job_id: str):\n        job = self.jobs.get(job_id)\n        if job is None:\n            raise LookupError(job_id)\n        application = {\"job_id\": job_id, \"applied_at\": self.clock.now()}\n        self.applications.save(application)\n        return application",
    aliases: ["service layer", "use case", "application service", "业务服务层", "用例"],
    whenToUse: "一个用户动作跨多个对象/依赖，且需要 transaction、权限或一致的业务规则。",
    commonMistake: "把 service 变成没有业务含义的巨大 Utils 类，或让它返回 HTTP response。",
  },
  {
    id: "design-adapter", category: "Engineering Design", title: "Adapter pattern", action: "把第三方接口转换为本地接口",
    description: "adapter 把外部 SDK 的名称、错误和数据格式限制在边界内，让业务代码依赖自己的协议。",
    syntax: "ExternalAdapter implements LocalProtocol",
    code: "class GmailNotifierAdapter:\n    def __init__(self, gmail_client):\n        self.client = gmail_client\n\n    def send(self, message: str) -> None:\n        self.client.messages().send(\n            userId=\"me\",\n            body={\"raw\": message},\n        ).execute()\n\n# Business code only knows notifier.send(message)",
    aliases: ["adapter pattern", "anti corruption layer", "third party wrapper", "适配器模式", "第三方封装"],
    whenToUse: "接入 Gmail、Notion、支付、云存储等你无法控制的 API。",
    commonMistake: "让第三方 SDK 类型穿过所有业务层，之后更换供应商需要修改整个项目。",
  },
  {
    id: "design-builder", category: "Engineering Design", title: "Builder: use only when needed", action: "判断是否需要 Builder",
    description: "Python 的 keyword arguments 和 dataclass 已经能处理多数对象创建；只有多阶段构造或复杂校验才值得 Builder。",
    syntax: "Builder().with_x(...).with_y(...).build()",
    code: "from dataclasses import dataclass\n\n@dataclass\nclass SearchQuery:\n    text: str\n    location: str | None = None\n    remote: bool = False\n\n# Prefer this for ordinary construction\nquery = SearchQuery(text=\"python\", location=\"Bay Area\", remote=True)\n\n# Add a Builder only if construction becomes multi-stage\n# and build() enforces important cross-field rules.",
    aliases: ["builder pattern", "fluent builder", "object construction", "建造者模式", "是否需要 builder"],
    whenToUse: "创建过程有多个阶段、条件分支或必须在 build 时验证跨字段不变量。",
    commonMistake: "照搬 Java Builder，为三个可选参数增加几十行样板代码。",
  },
  {
    id: "design-solid", category: "Engineering Design", title: "SOLID as change boundaries", action: "用 SOLID 判断代码为何难改",
    description: "SOLID 是发现变化耦合的工具，不是要求每个类只有一个方法；先观察变化原因再拆分。",
    syntax: "SRP · OCP · LSP · ISP · DIP",
    code: "# Hard to test/change: creates infrastructure itself\nclass BadReport:\n    def run(self):\n        database = ProductionDatabase()\n        return database.query(\"jobs\")\n\n# Dependency inversion: policy receives a small interface\nclass JobReport:\n    def __init__(self, jobs):\n        self.jobs = jobs\n\n    def run(self):\n        return self.jobs.list_for_report()",
    aliases: ["solid principles", "single responsibility", "dependency inversion", "open closed", "SOLID 原则", "依赖倒置"],
    whenToUse: "代码因为新增一种实现、测试或业务规则而反复修改同一大片区域时。",
    commonMistake: "为了“符合 SOLID”提前创建大量 interface 和只有一行的类，没有真实变化需求。",
  },
  {
    id: "design-domain-model", category: "Engineering Design", title: "Domain model vs data record", action: "决定 Dataclass 是否需要业务行为",
    description: "纯传输数据用简单 record；当数据有不变量和状态转换时，把规则放进领域对象。",
    syntax: "record = data only   |   entity.method() enforces rules",
    code: "from dataclasses import dataclass\nfrom enum import Enum\n\nclass Status(Enum):\n    SAVED = \"saved\"\n    APPLIED = \"applied\"\n\n@dataclass\nclass Application:\n    company: str\n    status: Status = Status.SAVED\n\n    def mark_applied(self) -> None:\n        if self.status is Status.APPLIED:\n            raise ValueError(\"already applied\")\n        self.status = Status.APPLIED",
    aliases: ["domain model", "anemic model", "dataclass vs entity", "领域模型", "贫血模型", "数据对象"],
    whenToUse: "状态转换必须始终遵守规则，且规则属于对象本身而不是传输协议。",
    commonMistake: "所有规则都放 service 里，把实体变成可被任意修改的 dict。",
  },
  {
    id: "design-resource-ownership", category: "Engineering Design", title: "Resource ownership & lifecycle", action: "明确谁创建、复用和关闭资源",
    description: "资源所有者负责关闭；短生命周期用 context manager，应用级 client 在启动创建、关闭时释放。",
    syntax: "owner creates -> lends -> closes",
    code: "from contextlib import contextmanager\n\n@contextmanager\ndef transaction(session_factory):\n    session = session_factory()\n    try:\n        yield session\n        session.commit()\n    except Exception:\n        session.rollback()\n        raise\n    finally:\n        session.close()\n\nwith transaction(SessionFactory) as session:\n    session.add(record)",
    aliases: ["resource ownership", "object lifecycle", "context manager cleanup", "资源所有权", "对象生命周期"],
    whenToUse: "数据库 session、HTTP client、文件、锁和线程池等必须释放的资源。",
    commonMistake: "函数关闭了调用方传入的共享资源，或每次操作都创建昂贵 client 却从不关闭。",
  },
];
