import type { PythonCheatItem } from "./pythonCheatsheet";

export const pythonOopCheatsheet: PythonCheatItem[] = [
  {
    id: "oop-class-instance", category: "OOP", title: "Class & instance", action: "定义 Class 并创建对象",
    description: "class 描述对象的状态与行为；self 指向当前实例。通常在 __init__ 中建立实例状态。",
    syntax: "class Name: def __init__(self, ...): ...",
    code: "class User:\n    def __init__(self, name: str):\n        self.name = name\n\n    def greet(self) -> str:\n        return f\"Hi, {self.name}\"\n\nada = User(\"Ada\")\nprint(ada.greet())  # Hi, Ada",
    aliases: ["python class", "create object", "class instance", "self init", "定义类", "创建对象", "实例化"],
  },
  {
    id: "oop-instance-class-attributes", category: "OOP", title: "Instance vs class attributes", action: "区分实例属性与类属性",
    description: "实例属性属于单个对象；类属性由所有实例共享。不要把 list/dict 等可变状态误放在类属性上。",
    syntax: "Class.shared   |   instance.owned",
    code: "class Account:\n    bank = \"Open Bank\"  # shared class attribute\n\n    def __init__(self, owner: str):\n        self.owner = owner   # per-instance attribute\n        self.tags = []       # each account gets its own list\n\na = Account(\"Ada\")\nb = Account(\"Linus\")\na.tags.append(\"admin\")\n# b.tags == []",
    aliases: ["class attribute", "instance attribute", "shared state", "mutable class variable", "类属性", "实例属性"],
  },
  {
    id: "oop-method-types", category: "OOP", title: "Instance, class & static methods", action: "选择实例 / 类 / 静态方法",
    description: "实例方法操作对象；classmethod 常做替代构造器；staticmethod 是与类相关但不依赖状态的工具函数。",
    syntax: "method(self) | @classmethod method(cls) | @staticmethod method()",
    code: "class Temperature:\n    def __init__(self, celsius: float):\n        self.celsius = celsius\n\n    @classmethod\n    def from_fahrenheit(cls, value: float):\n        return cls((value - 32) * 5 / 9)\n\n    @staticmethod\n    def is_freezing(value: float) -> bool:\n        return value <= 0\n\ntemp = Temperature.from_fahrenheit(32)",
    aliases: ["classmethod", "staticmethod", "instance method", "alternative constructor", "类方法", "静态方法", "实例方法"],
  },
  {
    id: "oop-property", category: "OOP", title: "Validated property", action: "用 Property 封装和校验属性",
    description: "property 保留普通属性的调用方式，同时集中校验逻辑；无必要时优先使用公开属性。",
    syntax: "@property   |   @name.setter",
    code: "class Product:\n    def __init__(self, price: float):\n        self.price = price\n\n    @property\n    def price(self) -> float:\n        return self._price\n\n    @price.setter\n    def price(self, value: float) -> None:\n        if value < 0:\n            raise ValueError(\"price must be non-negative\")\n        self._price = value\n\nbook = Product(29.0)",
    aliases: ["property getter setter", "encapsulation", "validate attribute", "private attribute", "属性校验", "封装", "getter setter"],
  },
  {
    id: "oop-inheritance-super", category: "OOP", title: "Inheritance & super", action: "继承父类并扩展行为",
    description: "子类复用父类接口并可覆盖方法；super() 按 MRO 调用下一层实现。只有真正的 is-a 关系才适合继承。",
    syntax: "class Child(Parent): super().__init__(...) ",
    code: "class Employee:\n    def __init__(self, name: str):\n        self.name = name\n\n    def describe(self) -> str:\n        return self.name\n\nclass Engineer(Employee):\n    def __init__(self, name: str, language: str):\n        super().__init__(name)\n        self.language = language\n\n    def describe(self) -> str:\n        return f\"{super().describe()} writes {self.language}\"",
    aliases: ["inheritance", "super", "override method", "parent child class", "继承", "父类", "子类", "方法重写"],
  },
  {
    id: "oop-abstract-base-class", category: "OOP", title: "Abstract base class", action: "用 ABC 强制子类实现接口",
    description: "ABC 适合需要共享运行时代码并禁止缺少实现的子类被实例化的场景。",
    syntax: "class Base(ABC): @abstractmethod def method(...): ...",
    code: "from abc import ABC, abstractmethod\n\nclass Storage(ABC):\n    @abstractmethod\n    def save(self, key: str, value: str) -> None:\n        raise NotImplementedError\n\nclass MemoryStorage(Storage):\n    def __init__(self):\n        self.data = {}\n\n    def save(self, key: str, value: str) -> None:\n        self.data[key] = value",
    aliases: ["abc", "abstract class", "abstractmethod", "interface", "抽象类", "抽象方法", "强制实现"],
  },
  {
    id: "oop-protocol", category: "OOP", title: "Protocol / structural typing", action: "用 Protocol 定义鸭子类型接口",
    description: "对象只要拥有所需方法就满足 Protocol，无需显式继承；适合解耦业务层与具体实现。",
    syntax: "class Interface(Protocol): def method(...): ...",
    code: "from typing import Protocol\n\nclass Notifier(Protocol):\n    def send(self, message: str) -> None: ...\n\nclass ConsoleNotifier:\n    def send(self, message: str) -> None:\n        print(message)\n\ndef publish(notifier: Notifier, message: str) -> None:\n    notifier.send(message)\n\npublish(ConsoleNotifier(), \"deployed\")",
    aliases: ["protocol", "structural typing", "duck typing", "interface python", "typing protocol", "鸭子类型", "接口", "解耦"],
  },
  {
    id: "oop-composition", category: "OOP", title: "Composition over inheritance", action: "用组合复用对象能力",
    description: "has-a 关系用组合：把可替换的协作者传入对象，比建立深继承树更容易测试和修改。",
    syntax: "class Service: def __init__(self, dependency): self.dependency = dependency",
    code: "class Engine:\n    def start(self) -> str:\n        return \"engine started\"\n\nclass Car:\n    def __init__(self, engine: Engine):\n        self.engine = engine\n\n    def drive(self) -> str:\n        return f\"{self.engine.start()}; driving\"\n\ncar = Car(Engine())",
    aliases: ["composition over inheritance", "has a relationship", "object composition", "组合优于继承", "对象组合"],
  },
  {
    id: "oop-dataclass", category: "OOP", title: "Dataclass", action: "用 Dataclass 定义数据对象",
    description: "dataclass 自动生成 __init__、__repr__、__eq__；适合以数据为主、行为较少的对象。",
    syntax: "@dataclass(frozen=False, slots=False)",
    code: "from dataclasses import dataclass, field\n\n@dataclass(slots=True)\nclass Job:\n    company: str\n    title: str\n    tags: list[str] = field(default_factory=list)\n    applied: bool = False\n\njob = Job(\"Acme\", \"Python Engineer\")\njob.tags.append(\"backend\")",
    aliases: ["dataclass", "data class", "field default factory", "slots", "数据类", "默认列表"],
  },
  {
    id: "oop-dunder-display-equality", category: "OOP", title: "repr, str & equality", action: "实现常用 Dunder 特殊方法",
    description: "__repr__ 面向开发者，__str__ 面向用户，__eq__ 定义值相等。dataclass 可自动生成这些方法。",
    syntax: "__repr__ | __str__ | __eq__",
    code: "class Money:\n    def __init__(self, amount: int, currency: str):\n        self.amount = amount\n        self.currency = currency\n\n    def __repr__(self) -> str:\n        return f\"Money({self.amount!r}, {self.currency!r})\"\n\n    def __str__(self) -> str:\n        return f\"{self.amount} {self.currency}\"\n\n    def __eq__(self, other: object) -> bool:\n        return isinstance(other, Money) and vars(self) == vars(other)",
    aliases: ["dunder methods", "magic methods", "repr str eq", "object equality", "特殊方法", "魔术方法", "对象相等"],
  },
  {
    id: "oop-iterator", category: "OOP", title: "Iterable object", action: "让自定义对象支持 For 循环",
    description: "__iter__ 返回迭代器；用 generator 实现最简洁，每次 yield 一个值。",
    syntax: "def __iter__(self): yield value",
    code: "class Countdown:\n    def __init__(self, start: int):\n        self.start = start\n\n    def __iter__(self):\n        for value in range(self.start, 0, -1):\n            yield value\n\nfor number in Countdown(3):\n    print(number)  # 3, 2, 1",
    aliases: ["iterator protocol", "iter next", "custom iterable", "for loop object", "迭代器", "可迭代对象", "yield"],
  },
  {
    id: "oop-context-manager", category: "OOP", title: "Context manager", action: "让对象支持 With 自动清理",
    description: "__enter__ 建立资源，__exit__ 保证清理；文件、锁、数据库事务都适用。",
    syntax: "__enter__ / __exit__   |   with resource as value:",
    code: "class ManagedConnection:\n    def __enter__(self):\n        print(\"connect\")\n        return self\n\n    def execute(self, query: str) -> None:\n        print(query)\n\n    def __exit__(self, exc_type, exc, traceback):\n        print(\"close\")\n        return False  # do not suppress exceptions\n\nwith ManagedConnection() as connection:\n    connection.execute(\"SELECT 1\")",
    aliases: ["context manager", "enter exit", "with statement", "resource cleanup", "上下文管理器", "自动清理资源"],
  },
  {
    id: "oop-callable-object", category: "OOP", title: "Callable object", action: "让对象像函数一样调用",
    description: "实现 __call__ 后实例可直接调用，适合需要保存配置或状态的函数对象。",
    syntax: "def __call__(self, ...): ...",
    code: "class Multiplier:\n    def __init__(self, factor: int):\n        self.factor = factor\n\n    def __call__(self, value: int) -> int:\n        return value * self.factor\n\ndouble = Multiplier(2)\nresult = double(5)  # 10",
    aliases: ["callable object", "call dunder", "function object", "functor", "可调用对象", "像函数调用"],
  },
  {
    id: "oop-generic-class", category: "OOP", title: "Generic class", action: "用泛型保留容器类型",
    description: "TypeVar 让同一个类安全保存不同类型，同时让类型检查器保留具体元素类型。",
    syntax: "class Box(Generic[T]): ...",
    code: "from typing import Generic, TypeVar\n\nT = TypeVar(\"T\")\n\nclass Box(Generic[T]):\n    def __init__(self, value: T):\n        self.value = value\n\n    def get(self) -> T:\n        return self.value\n\nnumber_box = Box[int](42)\nname_box = Box[str](\"Ada\")",
    aliases: ["generic class", "typevar", "generic type", "typed container", "泛型类", "类型变量"],
  },
  {
    id: "oop-mixin-mro", category: "OOP", title: "Mixin & MRO", action: "用 Mixin 添加小型横切能力",
    description: "Mixin 应小而专一，通常不持有核心状态。多继承调用顺序由 Class.mro() 决定。",
    syntax: "class Concrete(Mixin, Base): ...   |   Concrete.mro()",
    code: "class JsonMixin:\n    def to_dict(self) -> dict:\n        return vars(self)\n\nclass Record:\n    def __init__(self, name: str):\n        self.name = name\n\nclass JsonRecord(JsonMixin, Record):\n    pass\n\nrecord = JsonRecord(\"Ada\")\nprint(record.to_dict())\nprint(JsonRecord.mro())",
    aliases: ["mixin", "multiple inheritance", "mro", "method resolution order", "多继承", "方法解析顺序"],
  },
  {
    id: "oop-dependency-injection", category: "OOP", title: "Dependency injection", action: "注入依赖以便替换和测试",
    description: "由外部创建协作者并传给业务对象；生产环境传真实实现，测试传 fake，避免类内部硬编码基础设施。",
    syntax: "Service(dependency=implementation)",
    code: "class JobRepository:\n    def save(self, job: dict) -> None:\n        print(\"saved to database\", job)\n\nclass ApplicationService:\n    def __init__(self, repository):\n        self.repository = repository\n\n    def apply(self, company: str) -> None:\n        self.repository.save({\"company\": company})\n\nservice = ApplicationService(JobRepository())\nservice.apply(\"Acme\")",
    aliases: ["dependency injection", "inject dependency", "testable class", "fake repository", "依赖注入", "可测试设计"],
  },
  {
    id: "oop-factory", category: "OOP", title: "Factory pattern", action: "用 Factory 集中创建对象",
    description: "当创建逻辑取决于配置或需要隐藏具体类时，用 factory 返回统一接口的实现。",
    syntax: "def create(kind: str) -> Interface: ...",
    code: "class EmailNotifier:\n    def send(self, message: str) -> None:\n        print(\"email:\", message)\n\nclass SmsNotifier:\n    def send(self, message: str) -> None:\n        print(\"sms:\", message)\n\ndef create_notifier(kind: str):\n    factories = {\"email\": EmailNotifier, \"sms\": SmsNotifier}\n    try:\n        return factories[kind]()\n    except KeyError:\n        raise ValueError(f\"unknown notifier: {kind}\")\n\nnotifier = create_notifier(\"email\")",
    aliases: ["factory pattern", "factory method", "create object by type", "object creation", "工厂模式", "对象创建"],
  },
  {
    id: "oop-strategy", category: "OOP", title: "Strategy pattern", action: "运行时替换业务算法",
    description: "把变化的算法作为依赖传入，Context 只使用统一接口；相比大量 if/elif 更容易扩展和测试。",
    syntax: "Context(strategy).run(data)",
    code: "from typing import Protocol\n\nclass Discount(Protocol):\n    def apply(self, price: float) -> float: ...\n\nclass StudentDiscount:\n    def apply(self, price: float) -> float:\n        return price * 0.8\n\nclass Checkout:\n    def __init__(self, discount: Discount):\n        self.discount = discount\n\n    def total(self, price: float) -> float:\n        return self.discount.apply(price)\n\ncheckout = Checkout(StudentDiscount())",
    aliases: ["strategy pattern", "replace algorithm", "open closed principle", "策略模式", "替换算法", "行为模式"],
  },
];
