import type { PythonCheatItem } from "./pythonCheatsheet";

export const pythonInterviewCheatsheet: PythonCheatItem[] = [
  {
    id: "interview-grid-dfs", category: "Interview Patterns", title: "Grid DFS / flood fill", action: "递归遍历二维网格连通区域",
    description: "把每个格子视为图节点，向四个方向扩展；进入时立刻标记，避免重复访问。",
    syntax: "dfs(row, col); for dr, dc in directions: dfs(row+dr, col+dc)",
    code: "def count_area(grid, start_row, start_col):\n    rows, cols = len(grid), len(grid[0])\n    seen = set()\n\n    def dfs(row, col):\n        if not (0 <= row < rows and 0 <= col < cols): return 0\n        if grid[row][col] == 0 or (row, col) in seen: return 0\n        seen.add((row, col))\n        return 1 + sum(dfs(row+dr, col+dc) for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)))\n\n    return dfs(start_row, start_col)",
    aliases: ["grid dfs", "matrix dfs", "flood fill", "islands", "网格 DFS", "岛屿"],
    complexity: "time O(rows·cols) · space O(rows·cols)",
    whenToUse: "岛屿、连通块、边界填充，以及只需要完整探索而不关心最短步数。",
    commonMistake: "递归返回后才标记 visited，导致环中无限递归。",
  },
  {
    id: "interview-grid-bfs", category: "Interview Patterns", title: "Grid BFS shortest path", action: "在 Matrix 中求最短步数",
    description: "BFS 按距离分层；无权网格第一次到达终点就是最短路径。",
    syntax: "queue = deque([(row, col, distance)]); popleft()",
    code: "from collections import deque\n\ndef shortest_path(grid, start, target):\n    rows, cols = len(grid), len(grid[0])\n    queue = deque([(*start, 0)])\n    seen = {start}\n    while queue:\n        row, col, distance = queue.popleft()\n        if (row, col) == target: return distance\n        for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr, nc = row + dr, col + dc\n            if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] != 1 and (nr, nc) not in seen:\n                seen.add((nr, nc)); queue.append((nr, nc, distance + 1))\n    return -1",
    aliases: ["grid bfs", "matrix bfs", "shortest path grid", "maze", "网格 BFS", "迷宫最短路"],
    complexity: "time O(rows·cols) · space O(rows·cols)",
    whenToUse: "无权网格中的最少步数、最近目标或层级扩散。",
    commonMistake: "出队时才标记 seen，让同一格子被重复入队很多次。",
  },
  {
    id: "interview-tree-level-order", category: "Interview Patterns", title: "Tree level-order traversal", action: "按层遍历 Binary Tree",
    description: "每轮先记录当前 queue 长度，它就是这一层节点数。",
    syntax: "for _ in range(len(queue)): node = queue.popleft()",
    code: "from collections import deque\n\ndef level_order(root):\n    if not root: return []\n    queue, result = deque([root]), []\n    while queue:\n        level = []\n        for _ in range(len(queue)):\n            node = queue.popleft()\n            level.append(node.value)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level)\n    return result",
    aliases: ["tree level order", "binary tree bfs", "level traversal", "层序遍历", "树 BFS"],
    complexity: "time O(n) · space O(width)",
    whenToUse: "按深度分组、右视图、每层平均值和最短树深度。",
    commonMistake: "在遍历本层的过程中用变化后的 len(queue) 作为本层大小。",
  },
  {
    id: "interview-tree-diameter", category: "Interview Patterns", title: "Tree height & diameter", action: "后序遍历同时计算树高和直径",
    description: "每个节点先拿到左右子树高度，再用 left+right 更新穿过该节点的最长路径。",
    syntax: "height = 1 + max(left, right); diameter = max(diameter, left + right)",
    code: "def diameter(root):\n    best = 0\n\n    def height(node):\n        nonlocal best\n        if not node: return 0\n        left = height(node.left)\n        right = height(node.right)\n        best = max(best, left + right)\n        return 1 + max(left, right)\n\n    height(root)\n    return best",
    aliases: ["tree diameter", "tree height", "postorder tree", "二叉树直径", "树高"],
    complexity: "time O(n) · recursion O(height)",
    whenToUse: "答案由左右子树信息共同决定的树形 DP。",
    commonMistake: "把节点数量和边数量混在一起，造成 off-by-one。",
  },
  {
    id: "interview-tree-lca", category: "Interview Patterns", title: "Lowest common ancestor", action: "寻找二叉树最近公共祖先",
    description: "若左右子树分别找到目标，当前节点就是 LCA；否则向上传递非空结果。",
    syntax: "left = lca(node.left); right = lca(node.right)",
    code: "def lowest_common_ancestor(root, first, second):\n    if root is None or root is first or root is second:\n        return root\n    left = lowest_common_ancestor(root.left, first, second)\n    right = lowest_common_ancestor(root.right, first, second)\n    if left and right:\n        return root\n    return left or right",
    aliases: ["lowest common ancestor", "lca", "binary tree ancestor", "最近公共祖先", "树祖先"],
    complexity: "time O(n) · recursion O(height)",
    whenToUse: "普通二叉树中寻找两个已存在节点的最低共同分叉点。",
    commonMistake: "把 BST 的大小比较模板用于不满足排序条件的普通二叉树。",
  },
  {
    id: "interview-reverse-linked-list", category: "Interview Patterns", title: "Reverse linked list", action: "原地反转单向链表",
    description: "保存 next，反转 current.next，再同步移动 previous/current 三个指针。",
    syntax: "next_node = current.next; current.next = previous",
    code: "def reverse_list(head):\n    previous = None\n    current = head\n    while current:\n        next_node = current.next\n        current.next = previous\n        previous = current\n        current = next_node\n    return previous",
    aliases: ["reverse linked list", "linked list pointers", "反转链表", "链表指针"],
    complexity: "time O(n) · space O(1)",
    whenToUse: "链表反转、分段重排以及需要理解指针状态更新的题目。",
    commonMistake: "先覆盖 current.next 再保存原 next，导致后半条链表丢失。",
  },
  {
    id: "interview-merge-linked-lists", category: "Interview Patterns", title: "Merge sorted linked lists", action: "合并两个有序链表",
    description: "dummy 节点消除头节点特殊情况；tail 始终指向结果最后节点。",
    syntax: "dummy = tail = Node(0); tail.next = chosen",
    code: "def merge_lists(left, right, Node):\n    dummy = tail = Node(0)\n    while left and right:\n        if left.value <= right.value:\n            tail.next, left = left, left.next\n        else:\n            tail.next, right = right, right.next\n        tail = tail.next\n    tail.next = left or right\n    return dummy.next",
    aliases: ["merge linked lists", "sorted list merge", "dummy node", "合并链表", "哨兵节点"],
    complexity: "time O(m+n) · space O(1)",
    whenToUse: "合并有序链表、链表归并排序和 K 路合并的基础步骤。",
    commonMistake: "移动输入指针后忘记移动 tail，或返回 dummy 而不是 dummy.next。",
  },
  {
    id: "interview-top-k", category: "Interview Patterns", title: "Top K with heap", action: "用固定大小 Heap 找 Top K",
    description: "维护大小为 k 的最小堆，堆顶是当前 Top K 中最小值。",
    syntax: "heappush(heap, item); if len(heap) > k: heappop(heap)",
    code: "import heapq\n\ndef top_k(values, k):\n    heap = []\n    for value in values:\n        heapq.heappush(heap, value)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return sorted(heap, reverse=True)\n\nprint(top_k([5, 1, 9, 3, 7], 3))  # [9, 7, 5]",
    aliases: ["top k", "kth largest", "fixed heap", "前 K 个", "第 K 大"],
    complexity: "time O(n log k) · space O(k)",
    whenToUse: "数据很多但只需要最大/最小 K 个，尤其是流式数据。",
    commonMistake: "无条件排序整个数组 O(n log n)，或最大堆/最小堆方向选反。",
  },
  {
    id: "interview-memoization", category: "Interview Patterns", title: "Memoization with cache", action: "给递归状态加缓存",
    description: "@cache 让相同参数的子问题只计算一次；参数必须可哈希。",
    syntax: "@functools.cache def solve(state): ...",
    code: "from functools import cache\n\n@cache\ndef ways(steps: int) -> int:\n    if steps < 0: return 0\n    if steps == 0: return 1\n    return ways(steps - 1) + ways(steps - 2)\n\nprint(ways(20))\nways.cache_clear()",
    aliases: ["memoization", "lru cache recursion", "functools cache", "记忆化", "递归缓存"],
    complexity: "typically states × transitions",
    whenToUse: "递归树重复访问相同、可由少量参数表示的状态。",
    commonMistake: "把会变化的外部列表/全局状态隐含在函数里，缓存 key 无法反映真实状态。",
  },
  {
    id: "interview-grid-dp", category: "Interview Patterns", title: "Grid dynamic programming", action: "在二维网格中定义状态转移",
    description: "dp[row][col] 表示到达当前位置的答案；先明确依赖上方/左方，再确定遍历顺序。",
    syntax: "dp[r][c] = dp[r-1][c] + dp[r][c-1]",
    code: "def unique_paths(rows, cols):\n    dp = [1] * cols\n    for _ in range(1, rows):\n        for col in range(1, cols):\n            dp[col] += dp[col - 1]\n    return dp[-1]\n\nprint(unique_paths(3, 4))  # 10",
    aliases: ["grid dp", "matrix dynamic programming", "unique paths", "网格 DP", "二维动态规划"],
    complexity: "time O(rows·cols) · space O(cols)",
    whenToUse: "当前格答案只依赖固定方向的之前格子，且子问题大量重叠。",
    commonMistake: "没先定义 dp 状态含义就写公式，或空间压缩后按错误方向更新。",
  },
  {
    id: "interview-combination-sum", category: "Interview Patterns", title: "Backtracking combinations", action: "生成满足条件的组合",
    description: "start 控制选择范围避免顺序不同但集合相同的重复答案；remaining 用于剪枝。",
    syntax: "backtrack(start, remaining); choose -> recurse -> undo",
    code: "def combination_sum(candidates, target):\n    result, path = [], []\n    candidates.sort()\n\n    def backtrack(start, remaining):\n        if remaining == 0:\n            result.append(path.copy()); return\n        for index in range(start, len(candidates)):\n            value = candidates[index]\n            if value > remaining: break\n            path.append(value)\n            backtrack(index, remaining - value)\n            path.pop()\n\n    backtrack(0, target)\n    return result",
    aliases: ["combination sum", "backtracking combinations", "choose recurse undo", "组合总和", "回溯组合"],
    complexity: "exponential · recursion O(target/min value)",
    whenToUse: "列出全部选择方案，且每一步都能选择、递归、撤销。",
    commonMistake: "忘记 path.copy()，导致结果中的每项都引用同一个可变列表。",
  },
  {
    id: "interview-graph-cycle", category: "Interview Patterns", title: "Directed graph cycle detection", action: "用三色 DFS 检测有向环",
    description: "0 未访问、1 当前递归路径、2 已完成；遇到 color=1 的节点就是回边。",
    syntax: "color[node] = visiting; recurse; color[node] = done",
    code: "def has_cycle(graph):\n    color = {}\n\n    def dfs(node):\n        if color.get(node) == 1: return True\n        if color.get(node) == 2: return False\n        color[node] = 1\n        if any(dfs(neighbor) for neighbor in graph.get(node, [])):\n            return True\n        color[node] = 2\n        return False\n\n    return any(dfs(node) for node in graph if color.get(node, 0) == 0)",
    aliases: ["graph cycle detection", "directed cycle", "three color dfs", "有向图环", "三色 DFS"],
    complexity: "time O(V+E) · space O(V)",
    whenToUse: "课程依赖、构建依赖和有向图中判断是否存在循环。",
    commonMistake: "只维护 visited 集合，无法区分当前路径节点和已安全完成节点。",
  },
  {
    id: "interview-multi-source-bfs", category: "Interview Patterns", title: "Multi-source BFS", action: "从多个起点同时向外扩散",
    description: "把所有起点以距离 0 同时入队，得到每个节点到最近起点的距离。",
    syntax: "queue = deque(all_sources); distance[source] = 0",
    code: "from collections import deque\n\ndef nearest_source(graph, sources):\n    queue = deque(sources)\n    distance = {source: 0 for source in sources}\n    while queue:\n        node = queue.popleft()\n        for neighbor in graph.get(node, []):\n            if neighbor not in distance:\n                distance[neighbor] = distance[node] + 1\n                queue.append(neighbor)\n    return distance",
    aliases: ["multi source bfs", "nearest source", "rotting oranges", "多源 BFS", "同时扩散"],
    complexity: "time O(V+E) · space O(V)",
    whenToUse: "最近设施、腐烂传播、所有零到最近一等同时扩散问题。",
    commonMistake: "分别从每个起点跑一次 BFS，把 O(V+E) 变成重复的大量工作。",
  },
  {
    id: "interview-bit-manipulation", category: "Interview Patterns", title: "Bit manipulation toolkit", action: "读写、切换和统计二进制位",
    description: "位运算适合 flags、子集状态和 XOR 消除成对元素。",
    syntax: "n & mask | n | mask | n ^ mask | n & (n-1)",
    code: "number = 0b10110\nbit = 2\nmask = 1 << bit\n\nis_set = bool(number & mask)\nset_bit = number | mask\nclear_bit = number & ~mask\ntoggle_bit = number ^ mask\ncount = number.bit_count()\nremove_lowest_one = number & (number - 1)",
    aliases: ["bit manipulation", "bitmask", "xor", "bit count", "位运算", "位掩码"],
    complexity: "primitive operations O(1)",
    whenToUse: "集合规模较小可编码成 bitmask，或题目明确涉及二进制、奇偶配对。",
    commonMistake: "忘记运算符优先级；复杂表达式加括号，并注意 Python 负数使用无限符号位语义。",
  },
  {
    id: "interview-counting-bucket-sort", category: "Interview Patterns", title: "Counting & bucket sort", action: "利用有限值域做线性排序",
    description: "当值域 k 不大时统计频率，再按值重建结果；bucket 可按频率或区间分组。",
    syntax: "counts[value] += 1; emit value count times",
    code: "def counting_sort(values):\n    if not values: return []\n    low, high = min(values), max(values)\n    counts = [0] * (high - low + 1)\n    for value in values:\n        counts[value - low] += 1\n    return [\n        value\n        for offset, count in enumerate(counts)\n        for value in [offset + low] * count\n    ]",
    aliases: ["counting sort", "bucket sort", "frequency buckets", "计数排序", "桶排序"],
    complexity: "time O(n+k) · space O(k)",
    whenToUse: "整数值域或频率范围远小于 n log n 排序成本。",
    commonMistake: "值域跨度巨大时仍创建超大 counts 数组，空间反而更差。",
  },
  {
    id: "interview-sweep-line", category: "Interview Patterns", title: "Sweep line events", action: "把区间转换为有序事件",
    description: "起点 +1、终点 -1，按位置累积活动数量；同坐标事件顺序取决于区间边界定义。",
    syntax: "events.append((start,+1)); events.append((end,-1)); sort",
    code: "def max_overlap(intervals):\n    events = []\n    for start, end in intervals:\n        events.append((start, 1))\n        events.append((end, -1))\n    active = best = 0\n    for _, delta in sorted(events):\n        active += delta\n        best = max(best, active)\n    return best\n\n# Treats intervals as [start, end)",
    aliases: ["sweep line", "interval events", "maximum overlap", "扫描线", "区间重叠"],
    complexity: "time O(n log n) · space O(n)",
    whenToUse: "会议室数量、同时在线人数和区间覆盖计数。",
    commonMistake: "没有先确定 [start,end) 还是闭区间，导致同一坐标的事件排序错误。",
  },
  {
    id: "interview-bisect", category: "Interview Patterns", title: "Bisect insertion boundaries", action: "查找有序序列的左右插入点",
    description: "bisect_left 返回第一个 >= target 的位置；bisect_right 返回第一个 > target 的位置。",
    syntax: "bisect_left(values, target) | bisect_right(values, target)",
    code: "from bisect import bisect_left, bisect_right, insort\n\nvalues = [1, 2, 2, 2, 5]\nleft = bisect_left(values, 2)    # 1\nright = bisect_right(values, 2)  # 4\ncount = right - left             # 3\n\ninsort(values, 3)\n# [1, 2, 2, 2, 3, 5]",
    aliases: ["bisect left right", "binary insertion", "lower bound upper bound", "二分边界", "插入位置"],
    complexity: "search O(log n) · list insertion O(n)",
    whenToUse: "有序数组中找边界、计数范围或维护小型有序列表。",
    commonMistake: "以为 insort 整体是 O(log n)；查找快但 list 移动元素仍是 O(n)。",
  },
  {
    id: "interview-itertools", category: "Interview Patterns", title: "Itertools combinations", action: "快速生成排列、组合和笛卡尔积",
    description: "itertools 返回惰性迭代器，适合验证回溯结果或直接枚举小规模组合。",
    syntax: "combinations | permutations | product | accumulate",
    code: "from itertools import accumulate, combinations, permutations, product\n\nitems = [\"A\", \"B\", \"C\"]\npairs = list(combinations(items, 2))\norders = list(permutations(items, 2))\nbinary = list(product([0, 1], repeat=3))\nprefix = list(accumulate([2, 4, 1]))  # [2, 6, 7]",
    aliases: ["itertools", "combinations permutations", "cartesian product", "accumulate", "组合工具", "笛卡尔积"],
    complexity: "proportional to generated output",
    whenToUse: "输入很小且确实需要枚举所有结果，或快速构造测试数据。",
    commonMistake: "对大 n 直接 list(permutations(...))，阶乘级结果立即耗尽内存。",
  },
];
