import type { PythonCheatItem } from "./pythonCheatsheet";

export const pythonCoreCheatsheet: PythonCheatItem[] = [
  {
    id: "core-args-kwargs", category: "Core Patterns", title: "Flexible function parameters", action: "使用 *args / **kwargs / keyword-only",
    description: "*args 收集额外位置参数，**kwargs 收集额外关键字参数；单独的 * 强制后续参数必须写名字。",
    syntax: "def func(required, *args, keyword_only=False, **kwargs):",
    code: "def report(title, *scores, precision=1, **metadata):\n    average = sum(scores) / len(scores)\n    return {\n        \"title\": title,\n        \"average\": round(average, precision),\n        **metadata,\n    }\n\nreport(\"quiz\", 90, 95, precision=0, owner=\"Bruce\")",
    aliases: ["args kwargs", "keyword only", "variadic arguments", "参数解包", "可变参数"],
    whenToUse: "编写包装器、可配置 API，或确实需要转发一组未知参数时。",
    commonMistake: "为了省事让所有函数都接收 **kwargs，导致接口含义和拼写错误无法检查。",
  },
  {
    id: "core-typing", category: "Core Patterns", title: "Practical type hints", action: "标注 Optional / Literal / TypedDict / Callable",
    description: "类型标注不会自动做运行时校验，但能让编辑器、mypy/pyright 更早发现接口错误。",
    syntax: "str | None   |   Literal[...]   |   TypedDict   |   Callable[[...], R]",
    code: "from typing import Callable, Literal, TypedDict\n\nclass Job(TypedDict):\n    company: str\n    status: Literal[\"saved\", \"applied\"]\n\ndef transform(job: Job, formatter: Callable[[str], str]) -> str | None:\n    return formatter(job[\"company\"]) if job[\"company\"] else None",
    aliases: ["type hints", "optional union", "literal", "typeddict", "callable", "类型标注", "类型提示"],
    whenToUse: "公共函数、跨模块数据和依赖接口；优先标注边界，再逐步向内部扩展。",
    commonMistake: "把类型标注当作数据验证；外部输入仍需 Pydantic 或显式校验。",
  },
  {
    id: "core-generator", category: "Core Patterns", title: "Generator & yield", action: "惰性生成大量数据",
    description: "generator 每次 yield 一个值并暂停执行，不必一次把全部结果放进内存。",
    syntax: "def generate(...): yield value   |   (expr for item in items)",
    code: "def read_batches(rows, size=2):\n    batch = []\n    for row in rows:\n        batch.append(row)\n        if len(batch) == size:\n            yield batch\n            batch = []\n    if batch:\n        yield batch\n\nfor batch in read_batches(range(5)):\n    print(batch)",
    aliases: ["generator", "yield", "generator expression", "lazy iteration", "生成器", "惰性计算"],
    whenToUse: "流式读取文件、分页结果或任何可能很大的序列。",
    commonMistake: "generator 只能消费一次；调试时把它打印出来不会自动执行内部代码。",
  },
  {
    id: "core-decorator", category: "Core Patterns", title: "Function decorator", action: "编写保留元数据的装饰器",
    description: "装饰器接收函数并返回包装函数；functools.wraps 保留原函数名称、文档和签名信息。",
    syntax: "@decorator   |   @decorator(option=value)",
    code: "from functools import wraps\nimport time\n\ndef timed(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        started = time.perf_counter()\n        try:\n            return func(*args, **kwargs)\n        finally:\n            print(f\"{func.__name__}: {time.perf_counter()-started:.3f}s\")\n    return wrapper\n\n@timed\ndef work():\n    return sum(range(1000))",
    aliases: ["decorator", "functools wraps", "function wrapper", "装饰器", "带参数装饰器"],
    whenToUse: "日志、计时、权限、重试等跨多个函数的统一行为。",
    commonMistake: "忘记 @wraps，或让装饰器偷偷改变参数、返回值和异常语义。",
  },
  {
    id: "core-functional-tools", category: "Core Patterns", title: "Comprehension vs map/filter", action: "选择 Lambda、map、filter 或推导式",
    description: "简单转换/过滤通常用推导式更清楚；已有命名函数时 map/filter 也很自然。",
    syntax: "[f(x) for x in xs if test(x)]   |   map(f, xs)   |   filter(test, xs)",
    code: "numbers = [1, 2, 3, 4]\n\n# Preferred for a simple transform + filter\neven_squares = [n * n for n in numbers if n % 2 == 0]\n\n# Natural when a named function already exists\nnormalized = list(map(str.strip, [\" a \", \" b \"]))\npositive = list(filter(lambda n: n > 0, [-1, 0, 2]))",
    aliases: ["lambda map filter", "comprehension", "functional python", "匿名函数", "推导式"],
    whenToUse: "短小、无副作用的转换；超过一行逻辑就提取命名函数。",
    commonMistake: "嵌套多个 lambda/map/filter 追求短代码，结果比普通循环更难读。",
  },
  {
    id: "core-aggregation", category: "Core Patterns", title: "any, all, min & max", action: "用内置聚合代替手写循环",
    description: "any/all 会短路；min/max 的 key 指定比较依据但仍返回原对象。",
    syntax: "any(items) | all(items) | min(items, key=...) | max(items, key=...)",
    code: "jobs = [\n    {\"company\": \"A\", \"score\": 82},\n    {\"company\": \"B\", \"score\": 95},\n]\n\nhas_strong_match = any(job[\"score\"] >= 90 for job in jobs)\nall_named = all(job[\"company\"] for job in jobs)\nbest = max(jobs, key=lambda job: job[\"score\"])",
    aliases: ["any all", "min max key", "aggregation", "short circuit", "聚合", "最大最小"],
    whenToUse: "判断是否存在/全部满足条件，或按字段选择最佳对象。",
    commonMistake: "写 max(scores) 后再二次查找对象；应直接对对象集合使用 key。",
  },
  {
    id: "core-exception-chain", category: "Core Patterns", title: "Custom exceptions & chaining", action: "转换异常并保留根因",
    description: "在抽象边界把底层异常转换成领域异常；raise ... from error 保留完整因果链。",
    syntax: "raise DomainError(message) from original_error",
    code: "class ConfigError(Exception):\n    pass\n\ndef parse_port(raw: str) -> int:\n    try:\n        port = int(raw)\n    except ValueError as error:\n        raise ConfigError(f\"invalid port: {raw!r}\") from error\n    if not 1 <= port <= 65535:\n        raise ConfigError(\"port out of range\")\n    return port",
    aliases: ["custom exception", "raise from", "exception chaining", "自定义异常", "异常链"],
    whenToUse: "模块边界需要向调用方提供稳定、可理解的错误类型时。",
    commonMistake: "except Exception 后吞掉错误，或重新 raise 时丢失原始 traceback。",
  },
  {
    id: "core-match-case", category: "Core Patterns", title: "Structural pattern matching", action: "用 match / case 匹配数据形状",
    description: "match 不只是 switch；它能解构 mapping、sequence 和 class，并支持 guard。",
    syntax: "match value: case pattern if guard: ...",
    code: "def handle(event):\n    match event:\n        case {\"type\": \"job\", \"company\": company}:\n            return f\"new job at {company}\"\n        case {\"type\": \"score\", \"value\": value} if value >= 90:\n            return \"strong\"\n        case _:\n            return \"ignored\"",
    aliases: ["match case", "pattern matching", "structural pattern", "模式匹配", "switch python"],
    whenToUse: "输入有少量清晰、互斥的数据形状，且解构能减少嵌套判断时。",
    commonMistake: "把变量名当常量匹配；未限定的名字会捕获任意值。",
  },
  {
    id: "core-scope-closure", category: "Core Patterns", title: "LEGB, closure & nonlocal", action: "理解变量作用域并保存闭包状态",
    description: "名称按 Local → Enclosing → Global → Built-in 查找；nonlocal 修改最近的外层函数变量。",
    syntax: "nonlocal name   |   global name",
    code: "def make_counter(start=0):\n    count = start\n\n    def increment():\n        nonlocal count\n        count += 1\n        return count\n\n    return increment\n\ncounter = make_counter(10)\ncounter()  # 11\ncounter()  # 12",
    aliases: ["legb", "closure", "nonlocal", "global scope", "闭包", "作用域"],
    whenToUse: "小型状态函数、回调工厂或装饰器；复杂状态更适合类。",
    commonMistake: "在函数内赋值后以为会修改外层变量；没有 nonlocal 时会创建新的局部变量。",
  },
  {
    id: "core-copy", category: "Core Patterns", title: "Shallow vs deep copy", action: "正确复制嵌套对象",
    description: "浅拷贝只复制最外层容器；深拷贝递归复制内部对象，但不一定适合数据库连接等资源。",
    syntax: "copy.copy(value)   |   copy.deepcopy(value)",
    code: "from copy import copy, deepcopy\n\noriginal = {\"tags\": [\"python\"]}\nshallow = copy(original)\ndeep = deepcopy(original)\n\nshallow[\"tags\"].append(\"api\")\n# original changed because the nested list is shared\n# deep remains {\"tags\": [\"python\"]}",
    aliases: ["shallow copy", "deep copy", "copy deepcopy", "浅拷贝", "深拷贝"],
    whenToUse: "需要独立修改嵌套的纯数据结构；优先考虑不可变数据避免复制问题。",
    commonMistake: "以为 list.copy() 或 dict.copy() 会复制所有嵌套内容。",
  },
  {
    id: "core-mutable-default", category: "Core Patterns", title: "Mutable default argument", action: "避免默认 List / Dict 被共享",
    description: "默认参数在函数定义时只创建一次；用 None 作为哨兵，在每次调用中创建新容器。",
    syntax: "def func(items=None): items = [] if items is None else items",
    code: "def add_tag(tag: str, tags: list[str] | None = None) -> list[str]:\n    if tags is None:\n        tags = []\n    tags.append(tag)\n    return tags\n\nfirst = add_tag(\"python\")\nsecond = add_tag(\"react\")\n# first and second are independent",
    aliases: ["mutable default argument", "default list bug", "none sentinel", "可变默认参数", "默认列表陷阱"],
    whenToUse: "任何默认值需要是 list、dict、set 或自定义可变对象时。",
    commonMistake: "写 def func(items=[]):，导致不同调用共享并累积同一个列表。",
  },
  {
    id: "core-is-equality", category: "Core Patterns", title: "Identity vs equality", action: "区分 is 与 ==",
    description: "== 比较值是否相等；is 比较是否为同一个对象。None 是单例，使用 is None。",
    syntax: "left == right   |   value is None",
    code: "left = [1, 2]\nright = [1, 2]\n\nleft == right   # True: same value\nleft is right   # False: different objects\n\nresult = None\nif result is None:\n    print(\"missing\")",
    aliases: ["is vs equals", "identity equality", "is none", "对象身份", "值相等"],
    whenToUse: "通常用 == 比较值；只对 None 或明确的单例使用 is。",
    commonMistake: "用 is 比较字符串或数字；缓存行为可能让结果偶尔正确、偶尔错误。",
  },
];
