import type { PythonCheatItem } from "./pythonCheatsheet";

export const pythonProjectCheatsheet: PythonCheatItem[] = [
  {
    id: "project-modules-imports", category: "Project Engineering", title: "Modules, packages & imports", action: "组织 Package 与稳定 Import",
    description: "目录含 __init__.py 时是常规 package；应用代码优先使用从顶层包开始的绝对 import。",
    syntax: "from app.services.jobs import JobService",
    code: "# src/job_tracker/services/jobs.py\nclass JobService:\n    pass\n\n# src/job_tracker/main.py\nfrom job_tracker.services.jobs import JobService\n\ndef build_app() -> JobService:\n    return JobService()",
    aliases: ["python modules", "package imports", "absolute relative import", "模块", "包", "导入"],
    whenToUse: "代码超过几个文件时建立顶层包，并按业务能力而不是文件类型组织。",
    commonMistake: "修改 sys.path 或依赖当前工作目录，让代码只能从某个位置启动。",
  },
  {
    id: "project-pyproject", category: "Project Engineering", title: "pyproject.toml project", action: "建立现代 Python 项目配置",
    description: "pyproject.toml 集中项目元数据、依赖、构建系统和工具配置；src layout 避免误导入仓库根目录代码。",
    syntax: "[project] dependencies = [...]   |   [build-system]",
    code: "# pyproject.toml\n[build-system]\nrequires = [\"hatchling\"]\nbuild-backend = \"hatchling.build\"\n\n[project]\nname = \"job-tracker\"\nversion = \"0.1.0\"\nrequires-python = \">=3.12\"\ndependencies = [\"fastapi\", \"pydantic\"]\n\n[tool.pytest.ini_options]\npythonpath = [\"src\"]",
    aliases: ["pyproject toml", "python project structure", "src layout", "packaging", "项目结构", "项目配置"],
    exampleLabel: "PYPROJECT.TOML",
    whenToUse: "任何准备测试、协作或部署的项目，从第一天就建立。",
    commonMistake: "同时维护 setup.py、requirements.txt 和 pyproject 三套互相冲突的依赖来源。",
  },
  {
    id: "project-venv-dependencies", category: "Project Engineering", title: "Virtual environment & dependencies", action: "隔离环境并固定依赖",
    description: "每个项目使用独立虚拟环境；声明直接依赖并使用 lock 文件保证可重复安装。",
    syntax: "python -m venv .venv   |   python -m pip install -e .",
    code: "# Create and activate\npython -m venv .venv\nsource .venv/bin/activate\n\n# Install this project in editable mode\npython -m pip install -e \".[dev]\"\n\n# Confirm which interpreter is active\npython -c \"import sys; print(sys.executable)\"",
    aliases: ["venv", "virtual environment", "pip dependencies", "lock file", "虚拟环境", "依赖管理"],
    exampleLabel: "TERMINAL",
    whenToUse: "所有项目，包括一次性脚本，只要它安装了第三方包。",
    commonMistake: "把包装到全局/base 环境，之后无法复现本机为什么能运行。",
  },
  {
    id: "project-logging", category: "Project Engineering", title: "Structured application logging", action: "用 Logging 记录可诊断信息",
    description: "模块使用 getLogger(__name__)；入口统一配置 level/format，异常位置用 logger.exception 保留堆栈。",
    syntax: "logger = logging.getLogger(__name__)   |   logger.info(...)",
    code: "import logging\n\nlogger = logging.getLogger(__name__)\n\ndef process(job_id: str) -> None:\n    logger.info(\"processing job_id=%s\", job_id)\n    try:\n        int(job_id)\n    except ValueError:\n        logger.exception(\"invalid job_id=%s\", job_id)\n        raise\n\nlogging.basicConfig(level=logging.INFO, format=\"%(levelname)s %(name)s %(message)s\")",
    aliases: ["python logging", "logger exception", "structured logs", "日志", "记录异常"],
    whenToUse: "长期运行的服务、定时任务和任何失败后需要追查原因的程序。",
    commonMistake: "用 f-string 提前格式化所有日志，或在库模块里调用 basicConfig。",
  },
  {
    id: "project-environment-config", category: "Project Engineering", title: "Environment configuration", action: "从环境变量读取并校验配置",
    description: "配置来自环境，代码提供默认值并在启动时一次性校验；secret 不写进仓库。",
    syntax: "os.environ[name]   |   os.getenv(name, default)",
    code: "import os\nfrom dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Settings:\n    database_url: str\n    debug: bool\n\ndef load_settings() -> Settings:\n    return Settings(\n        database_url=os.environ[\"DATABASE_URL\"],\n        debug=os.getenv(\"DEBUG\", \"false\").lower() == \"true\",\n    )",
    aliases: ["environment variables", "env config", "secrets", "settings", "环境变量", "配置管理"],
    whenToUse: "数据库地址、API key、环境开关等部署时变化的设置。",
    commonMistake: "在模块 import 时到处读取环境变量，造成测试难以覆盖且错误出现得太晚。",
  },
  {
    id: "project-pathlib", category: "Project Engineering", title: "Pathlib directories & files", action: "跨平台操作路径和目录",
    description: "Path 对象组合路径、创建目录、遍历文件；避免手写 / 和字符串拼接。",
    syntax: "Path(...).mkdir() | glob() | read_text() | write_text()",
    code: "from pathlib import Path\n\ndata_dir = Path.home() / \"daily-dashboard\" / \"data\"\ndata_dir.mkdir(parents=True, exist_ok=True)\n\nfor json_file in data_dir.glob(\"*.json\"):\n    print(json_file.name, json_file.stat().st_size)\n\noutput = data_dir / \"summary.txt\"\noutput.write_text(\"ready\\n\", encoding=\"utf-8\")",
    aliases: ["pathlib", "create directory", "glob files", "file paths", "路径操作", "创建目录"],
    whenToUse: "几乎所有本地文件路径操作；Path 可以直接传给多数现代 API。",
    commonMistake: "用字符串相加构造路径，或忘记显式指定文本编码。",
  },
  {
    id: "project-datetime-timezone", category: "Project Engineering", title: "Timezone-aware datetime", action: "正确处理日期、时区和 ISO 时间",
    description: "内部保存 aware datetime/UTC，边界显示时转换用户时区；zoneinfo 使用 IANA 时区数据库。",
    syntax: "datetime.now(timezone.utc)   |   value.astimezone(ZoneInfo(...))",
    code: "from datetime import datetime, timezone\nfrom zoneinfo import ZoneInfo\n\nnow_utc = datetime.now(timezone.utc)\nbay_area = now_utc.astimezone(ZoneInfo(\"America/Los_Angeles\"))\nserialized = now_utc.isoformat()\nrestored = datetime.fromisoformat(serialized)\n\nprint(bay_area.strftime(\"%Y-%m-%d %H:%M %Z\"))",
    aliases: ["datetime timezone", "zoneinfo", "utc", "isoformat", "日期时间", "时区"],
    whenToUse: "日程、数据库时间戳、跨时区用户和定时任务。",
    commonMistake: "混合 naive 和 aware datetime，或把固定 UTC offset 当成真实时区。",
  },
  {
    id: "project-regex", category: "Project Engineering", title: "Regular expressions", action: "用 Regex 提取和替换结构化文本",
    description: "使用 raw string 编写模式；fullmatch 验证整个字符串，search 查找任意位置。",
    syntax: "re.fullmatch(pattern, text) | re.search() | re.sub()",
    code: "import re\n\nJOB_ID = re.compile(r\"JOB-(?P<number>\\d{4})\")\n\nmatch = JOB_ID.fullmatch(\"JOB-2048\")\nif match:\n    number = int(match.group(\"number\"))\n\nclean = re.sub(r\"\\s+\", \" \", \"Python   Engineer\").strip()",
    aliases: ["regex", "regular expression", "re fullmatch search sub", "正则表达式", "文本提取"],
    whenToUse: "结构规则明确的短文本提取、验证和批量替换。",
    commonMistake: "用一个巨大 regex 解析 HTML/JSON，或忘记 raw string 导致反斜杠转义错误。",
  },
  {
    id: "project-csv", category: "Project Engineering", title: "CSV read & write", action: "安全读写 CSV 表格",
    description: "使用 csv.DictReader/DictWriter 保留列名；打开文件时传 newline='' 避免空行问题。",
    syntax: "csv.DictReader(file)   |   csv.DictWriter(file, fieldnames=...)",
    code: "import csv\n\nwith open(\"jobs.csv\", newline=\"\", encoding=\"utf-8\") as file:\n    jobs = list(csv.DictReader(file))\n\nwith open(\"output.csv\", \"w\", newline=\"\", encoding=\"utf-8\") as file:\n    writer = csv.DictWriter(file, fieldnames=[\"company\", \"title\"])\n    writer.writeheader()\n    writer.writerows(jobs)",
    aliases: ["csv reader writer", "dictreader", "dictwriter", "读写 csv", "表格文件"],
    whenToUse: "与 spreadsheet 或简单数据导入导出交互。",
    commonMistake: "直接 split(',')，无法正确处理引号、逗号和换行字段。",
  },
  {
    id: "project-serialization", category: "Project Engineering", title: "Serialization boundary", action: "把对象转换成稳定 JSON 数据",
    description: "序列化层只输出 JSON 支持的基本类型；显式处理 datetime、enum 和 dataclass。",
    syntax: "json.dumps(to_dict(value))   |   json.loads(text)",
    code: "import json\nfrom dataclasses import asdict, dataclass\nfrom datetime import datetime, timezone\n\n@dataclass\nclass Event:\n    name: str\n    created_at: datetime\n\nevent = Event(\"apply\", datetime.now(timezone.utc))\npayload = asdict(event)\npayload[\"created_at\"] = event.created_at.isoformat()\ntext = json.dumps(payload, ensure_ascii=False)",
    aliases: ["serialization", "json datetime", "dataclass asdict", "序列化", "对象转 json"],
    whenToUse: "API、文件、消息队列和缓存边界。",
    commonMistake: "直接 dump 任意对象或 vars(obj)，意外泄露内部字段并丢失 schema 控制。",
  },
  {
    id: "project-http-client", category: "Project Engineering", title: "HTTP client with errors", action: "发送 HTTP 请求并处理超时和状态码",
    description: "所有外部请求必须有 timeout；raise_for_status 把非 2xx 响应转成异常。",
    syntax: "httpx.Client(timeout=...)   |   response.raise_for_status()",
    code: "import httpx\n\ndef fetch_job(job_id: str) -> dict:\n    try:\n        with httpx.Client(timeout=10.0) as client:\n            response = client.get(f\"https://api.example.com/jobs/{job_id}\")\n            response.raise_for_status()\n            return response.json()\n    except httpx.TimeoutException as error:\n        raise RuntimeError(\"job API timed out\") from error",
    aliases: ["http request", "httpx", "requests timeout", "api client", "HTTP 请求", "网络请求"],
    whenToUse: "调用 REST API；把 client 注入服务以便复用连接和测试。",
    commonMistake: "不设置 timeout、对所有错误无限重试，或每次请求都重新创建长期 client。",
  },
  {
    id: "project-async-await", category: "Project Engineering", title: "Async / await basics", action: "编写非阻塞 I/O 协程",
    description: "async def 返回 coroutine；只有 await 后才执行。异步适合网络/磁盘等待，不会让 CPU 计算自动变快。",
    syntax: "async def func(): result = await operation()",
    code: "import asyncio\n\nasync def fetch(name: str) -> str:\n    await asyncio.sleep(0.1)  # stand-in for async I/O\n    return f\"loaded {name}\"\n\nasync def main():\n    result = await fetch(\"jobs\")\n    print(result)\n\nasyncio.run(main())",
    aliases: ["async await", "coroutine", "asyncio run", "异步", "协程"],
    whenToUse: "大量时间花在等待网络、数据库或其他支持 async 的 I/O。",
    commonMistake: "在 async 函数中调用 time.sleep 或同步 HTTP 客户端，阻塞整个 event loop。",
  },
  {
    id: "project-async-gather", category: "Project Engineering", title: "Concurrent async tasks", action: "用 asyncio.gather 并发等待多个任务",
    description: "gather 并发调度多个协程并按输入顺序返回结果；TaskGroup 在现代 Python 中提供更清晰的失败语义。",
    syntax: "results = await asyncio.gather(*(work(item) for item in items))",
    code: "import asyncio\n\nasync def check(company: str) -> str:\n    await asyncio.sleep(0.1)\n    return company.upper()\n\nasync def main():\n    companies = [\"google\", \"meta\", \"apple\"]\n    results = await asyncio.gather(*(check(name) for name in companies))\n    print(results)\n\nasyncio.run(main())",
    aliases: ["asyncio gather", "concurrent async", "taskgroup", "并发协程", "批量异步"],
    whenToUse: "多个互不依赖的 I/O 操作可以同时等待时；必要时用 Semaphore 限制并发量。",
    commonMistake: "一次创建数万任务压垮远端服务，或用 return_exceptions=True 后忘记检查错误。",
  },
  {
    id: "project-concurrency-choice", category: "Project Engineering", title: "Threads vs processes vs async", action: "选择正确的并发模型",
    description: "async 适合大量协作式 I/O；threads 适合同步阻塞 I/O；processes 绕过 GIL 执行 CPU 密集任务。",
    syntax: "asyncio | ThreadPoolExecutor | ProcessPoolExecutor",
    code: "from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor\n\ndef blocking_io(url):\n    return f\"loaded {url}\"\n\ndef cpu_work(number):\n    return sum(i * i for i in range(number))\n\ndef main():\n    with ThreadPoolExecutor() as pool:\n        pages = list(pool.map(blocking_io, [\"a\", \"b\"]))\n    with ProcessPoolExecutor() as pool:\n        totals = list(pool.map(cpu_work, [10_000, 20_000]))\n    return pages, totals\n\nif __name__ == \"__main__\":\n    print(main())",
    aliases: ["threading multiprocessing", "threads vs processes", "gil", "concurrency", "线程", "进程", "并发选择"],
    whenToUse: "先判断瓶颈是等待 I/O 还是 CPU，再选择模型并测量。",
    commonMistake: "用线程加速纯 Python CPU 计算，或在多进程任务间传输巨大对象。",
  },
  {
    id: "project-pytest-basic", category: "Project Engineering", title: "Pytest arrange-act-assert", action: "编写清晰的单元测试",
    description: "测试只验证一个行为，名字说明场景和结果；Arrange/Act/Assert 让结构直观。",
    syntax: "def test_behavior(): arrange; result = act; assert result == expected",
    code: "def calculate_total(prices):\n    return round(sum(prices), 2)\n\ndef test_calculate_total_adds_prices():\n    # Arrange\n    prices = [10.25, 2.50]\n    # Act\n    result = calculate_total(prices)\n    # Assert\n    assert result == 12.75",
    aliases: ["pytest", "unit test", "arrange act assert", "单元测试", "测试函数"],
    whenToUse: "业务规则、数据转换和 bug 修复；失败应能明确指出哪项行为坏了。",
    commonMistake: "一个测试覆盖十种行为，失败后无法判断原因。",
  },
  {
    id: "project-pytest-fixture", category: "Project Engineering", title: "Pytest fixture", action: "复用测试准备和清理逻辑",
    description: "fixture 提供测试依赖并可在 yield 后清理；scope 应尽量小，保持测试隔离。",
    syntax: "@pytest.fixture def resource(): yield value",
    code: "import pytest\n\n@pytest.fixture\ndef job_store(tmp_path):\n    path = tmp_path / \"jobs.json\"\n    path.write_text(\"[]\", encoding=\"utf-8\")\n    yield path\n\ndef test_store_starts_empty(job_store):\n    assert job_store.read_text(encoding=\"utf-8\") == \"[]\"",
    aliases: ["pytest fixture", "test setup teardown", "tmp_path", "测试夹具", "测试准备"],
    whenToUse: "多个测试共享相同依赖构造或必须可靠清理资源时。",
    commonMistake: "创建巨大的全局 fixture，隐藏每个测试真正依赖了什么。",
  },
  {
    id: "project-pytest-parametrize", category: "Project Engineering", title: "Parametrized tests", action: "用多组输入验证同一行为",
    description: "parametrize 把输入/期望值表格化，每一组仍是独立测试案例。",
    syntax: "@pytest.mark.parametrize(('input','expected'), cases)",
    code: "import pytest\n\n@pytest.mark.parametrize(\n    (\"score\", \"expected\"),\n    [(95, \"strong\"), (80, \"medium\"), (50, \"weak\")],\n)\ndef test_rank_score(score, expected):\n    if score >= 90: result = \"strong\"\n    elif score >= 70: result = \"medium\"\n    else: result = \"weak\"\n    assert result == expected",
    aliases: ["pytest parametrize", "table driven test", "test cases", "参数化测试", "多组测试"],
    whenToUse: "同一规则需要覆盖边界值、正常值和错误输入。",
    commonMistake: "在一个参数行塞入过多无关字段，掩盖其实存在多个不同的行为。",
  },
  {
    id: "project-mocking", category: "Project Engineering", title: "Mock external boundaries", action: "替换网络、时间和外部服务",
    description: "在被测模块查找依赖的位置 patch；优先注入小型 fake，mock 只用于真正的外部边界。",
    syntax: "with patch('module.symbol') as mock: ...",
    code: "from unittest.mock import Mock\n\ndef notify(client, message: str) -> None:\n    client.send(message)\n\ndef test_notify_sends_exact_message():\n    client = Mock()\n    notify(client, \"interview tomorrow\")\n    client.send.assert_called_once_with(\"interview tomorrow\")",
    aliases: ["mock patch", "unittest mock", "test double", "fake dependency", "模拟依赖", "测试替身"],
    whenToUse: "网络、邮件、系统时间等慢、不稳定或有外部副作用的边界。",
    commonMistake: "mock 被测对象内部每一个方法，让重构破坏测试但真实行为从未被验证。",
  },
  {
    id: "project-debugging", category: "Project Engineering", title: "Breakpoint & traceback", action: "定位异常和检查运行时状态",
    description: "breakpoint() 进入调试器；traceback.format_exc() 在需要记录完整错误时保留调用链。",
    syntax: "breakpoint()   |   traceback.format_exc()",
    code: "import traceback\n\ndef divide(left, right):\n    # breakpoint()  # inspect left/right interactively\n    return left / right\n\ntry:\n    divide(10, 0)\nexcept ZeroDivisionError:\n    details = traceback.format_exc()\n    print(details)",
    aliases: ["breakpoint pdb", "traceback", "debug python", "调试", "错误堆栈"],
    whenToUse: "值与预期不符时在最靠近错误的位置暂停，并沿数据来源向上追踪。",
    commonMistake: "只在最终异常行盲目 print；根因通常发生在更早的数据转换处。",
  },
  {
    id: "project-profiling", category: "Project Engineering", title: "Measure performance", action: "用 timeit / cProfile 找真正瓶颈",
    description: "先 profile 再优化；timeit 比较小片段，cProfile 查看完整程序的累计调用时间。",
    syntax: "python -m timeit ...   |   python -m cProfile -s cumulative app.py",
    code: "from timeit import timeit\n\nlist_time = timeit(\n    \"target in values\",\n    setup=\"values=list(range(10000)); target=9999\",\n    number=1000,\n)\nset_time = timeit(\n    \"target in values\",\n    setup=\"values=set(range(10000)); target=9999\",\n    number=1000,\n)\nprint(list_time, set_time)",
    aliases: ["profile python", "cprofile", "timeit", "performance", "性能分析", "基准测试"],
    whenToUse: "用户能感知到慢，或资源成本确实重要时；用生产规模数据测量。",
    commonMistake: "根据直觉微优化语法，却忽略数据库查询、网络和算法复杂度。",
  },
  {
    id: "project-cli", category: "Project Engineering", title: "Command-line interface", action: "用 argparse 建立可靠 CLI",
    description: "argparse 自动生成帮助、校验类型并处理必填参数；main(argv) 结构便于测试。",
    syntax: "parser.add_argument(...)   |   args = parser.parse_args(argv)",
    code: "import argparse\n\ndef main(argv=None):\n    parser = argparse.ArgumentParser(description=\"Generate dashboard\")\n    parser.add_argument(\"--date\", required=True)\n    parser.add_argument(\"--open\", action=\"store_true\")\n    args = parser.parse_args(argv)\n    return f\"generate {args.date}, open={args.open}\"\n\nif __name__ == \"__main__\":\n    print(main())",
    aliases: ["argparse", "python cli", "command line arguments", "命令行", "参数解析"],
    whenToUse: "脚本需要被人、launchd/cron 或 CI 可靠调用时。",
    commonMistake: "直接读取 sys.argv 下标，没有帮助、类型验证或可测试入口。",
  },
  {
    id: "project-pydantic", category: "Project Engineering", title: "Pydantic validation", action: "在系统边界校验外部数据",
    description: "BaseModel 解析并验证 API/config 数据；字段 validator 表达跨值规则前先保持 schema 简单。",
    syntax: "class Model(BaseModel): field: Type = Field(...) ",
    code: "from pydantic import BaseModel, Field, HttpUrl\n\nclass JobInput(BaseModel):\n    company: str = Field(min_length=1, max_length=100)\n    url: HttpUrl\n    score: int = Field(ge=0, le=100)\n\npayload = JobInput.model_validate({\n    \"company\": \"Acme\",\n    \"url\": \"https://example.com/job\",\n    \"score\": 92,\n})",
    aliases: ["pydantic", "basemodel", "data validation", "schema", "数据校验", "输入模型"],
    whenToUse: "HTTP、消息、配置等不可信输入进入系统的边界。",
    commonMistake: "让 Pydantic model 同时承担数据库实体和全部业务行为，造成层之间强耦合。",
  },
  {
    id: "project-fastapi-layers", category: "Project Engineering", title: "FastAPI route-service-repository", action: "分离 HTTP、业务逻辑与数据访问",
    description: "route 负责协议转换，service 负责用例，repository 负责持久化；依赖方向指向业务核心。",
    syntax: "route -> service -> repository",
    code: "from fastapi import APIRouter, Depends\n\nrouter = APIRouter()\n\nclass JobService:\n    def __init__(self, repository):\n        self.repository = repository\n\n    def list_jobs(self):\n        return self.repository.list()\n\ndef get_service() -> JobService:\n    return JobService(repository=InMemoryJobRepository())\n\n@router.get(\"/jobs\")\ndef list_jobs(service: JobService = Depends(get_service)):\n    return service.list_jobs()",
    aliases: ["fastapi architecture", "route service repository", "dependency injection fastapi", "FastAPI 分层", "接口分层"],
    whenToUse: "只要 endpoint 包含真实业务规则或需要替换数据库实现。",
    commonMistake: "把 SQL、业务判断和响应格式全部写进 route function。",
  },
  {
    id: "project-sql-transaction", category: "Project Engineering", title: "Database transaction & session", action: "明确提交、回滚和 Session 生命周期",
    description: "一个业务用例通常对应一个 transaction；成功 commit，异常 rollback，最终关闭 session。",
    syntax: "with Session(engine) as session: with session.begin(): ...",
    code: "from sqlalchemy.orm import Session\n\ndef create_application(engine, application):\n    with Session(engine) as session:\n        try:\n            with session.begin():\n                session.add(application)\n                session.flush()\n            return application.id\n        except Exception:\n            session.rollback()\n            raise\n        # Session closes at the end of the outer with",
    aliases: ["sql transaction", "sqlalchemy session", "commit rollback", "数据库事务", "会话生命周期"],
    whenToUse: "多个数据库写入必须全部成功或全部失败，或需要稳定读取视图时。",
    commonMistake: "共享全局 session、在 repository 内偷偷 commit，导致业务用例无法原子化。",
  },
];
