import type { PythonCheatItem } from "./pythonCheatsheet";

export const pythonDsaCheatsheet: PythonCheatItem[] = [
  {
    id: "ds-stack", category: "Data Structures", title: "Stack with list", action: "实现 Stack / 栈",
    description: "后进先出（LIFO）。Python list 尾部 append/pop 都是均摊 O(1)。", syntax: "append(value) / pop() / stack[-1]",
    code: "stack = []\nstack.append(10)\nstack.append(20)\ntop = stack[-1]       # 20\nvalue = stack.pop()   # 20\nis_empty = not stack",
    aliases: ["implement stack", "stack implementation", "lifo", "push pop", "实现栈", "单调栈基础"],
    complexity: "push O(1) amortized · pop O(1) · space O(n)",
  },
  {
    id: "ds-queue", category: "Data Structures", title: "Queue with deque", action: "实现 Queue / 队列",
    description: "先进先出（FIFO）。不要用 list.pop(0)，它需要移动后续全部元素。", syntax: "deque.append(value) / deque.popleft()",
    code: "from collections import deque\n\nqueue = deque()\nqueue.append(10)\nqueue.append(20)\nfront = queue[0]        # 10\nvalue = queue.popleft() # 10",
    aliases: ["implement queue", "queue implementation", "fifo", "enqueue dequeue", "实现队列", "bfs queue"],
    complexity: "enqueue O(1) · dequeue O(1) · space O(n)",
  },
  {
    id: "ds-linked-list", category: "Data Structures", title: "Singly linked list", action: "实现单向 Linked List",
    description: "每个节点保存 value 和 next；头部插入 O(1)，按位置访问 O(n)。", syntax: "Node(value, next) / head = Node(value, head)",
    code: "class Node:\n    def __init__(self, value, next_node=None):\n        self.value = value\n        self.next = next_node\n\nhead = None\nfor value in [3, 2, 1]:\n    head = Node(value, head)\n\ncurrent = head\nwhile current:\n    print(current.value)\n    current = current.next",
    aliases: ["implement linked list", "singly linked list", "linked list node", "单向链表", "实现链表"],
    complexity: "prepend O(1) · search O(n) · space O(n)",
  },
  {
    id: "ds-doubly-linked-list", category: "Data Structures", title: "Doubly linked list", action: "实现双向 Linked List",
    description: "节点同时保存 prev/next；已知节点时可在 O(1) 内删除。", syntax: "Node(value, prev, next) / unlink(node)",
    code: "class Node:\n    def __init__(self, value):\n        self.value = value\n        self.prev = self.next = None\n\ndef unlink(node):\n    if node.prev:\n        node.prev.next = node.next\n    if node.next:\n        node.next.prev = node.prev\n    node.prev = node.next = None",
    aliases: ["doubly linked list", "double linked list", "prev next node", "双向链表", "删除链表节点"],
    complexity: "known-node delete O(1) · search O(n) · space O(n)",
  },
  {
    id: "ds-hash-table", category: "Data Structures", title: "Hash table with chaining", action: "实现 Hash Map / 哈希表",
    description: "把 key 哈希到 bucket；冲突时在 bucket 中链式存储键值对。生产代码直接使用 dict。", syntax: "bucket = hash(key) % capacity",
    code: "class HashMap:\n    def __init__(self, capacity=8):\n        self.buckets = [[] for _ in range(capacity)]\n\n    def put(self, key, value):\n        bucket = self.buckets[hash(key) % len(self.buckets)]\n        for index, (old_key, _) in enumerate(bucket):\n            if old_key == key:\n                bucket[index] = (key, value)\n                return\n        bucket.append((key, value))\n\n    def get(self, key, default=None):\n        bucket = self.buckets[hash(key) % len(self.buckets)]\n        return next((v for k, v in bucket if k == key), default)",
    aliases: ["implement hash map", "hash table", "separate chaining", "hash collision", "实现哈希表", "实现字典"],
    complexity: "average get/put O(1) · worst O(n) · space O(n)",
  },
  {
    id: "ds-binary-tree", category: "Data Structures", title: "Binary tree nodes", action: "实现 Binary Tree / 二叉树",
    description: "每个节点最多有 left/right 两个子节点；它只描述结构，不自动满足排序规则。", syntax: "TreeNode(value, left=None, right=None)",
    code: "class TreeNode:\n    def __init__(self, value, left=None, right=None):\n        self.value = value\n        self.left = left\n        self.right = right\n\nroot = TreeNode(1,\n    left=TreeNode(2),\n    right=TreeNode(3),\n)",
    aliases: ["implement binary tree", "tree node", "binary tree class", "实现二叉树", "树节点"],
    complexity: "node access O(1) · full traversal O(n) · space O(n)",
  },
  {
    id: "ds-bst", category: "Data Structures", title: "Binary search tree", action: "实现 BST 插入与查找",
    description: "左子树较小、右子树较大；未平衡时最坏会退化成链表。", syntax: "insert(root, value) / search(root, target)",
    code: "def insert(root, value):\n    if root is None:\n        return TreeNode(value)\n    if value < root.value:\n        root.left = insert(root.left, value)\n    elif value > root.value:\n        root.right = insert(root.right, value)\n    return root\n\ndef search(root, target):\n    while root and root.value != target:\n        root = root.left if target < root.value else root.right\n    return root",
    aliases: ["implement bst", "binary search tree", "bst insert", "bst search", "二叉搜索树", "搜索树"],
    complexity: "average O(log n) · worst O(n) · recursion O(h)",
  },
  {
    id: "ds-heap", category: "Data Structures", title: "Min heap with heapq", action: "实现 Heap / 优先队列",
    description: "heapq 把 list 维护成最小堆；最大堆可存负数或自定义可比较对象。", syntax: "heapify / heappush / heappop",
    code: "import heapq\n\nheap = [5, 1, 4]\nheapq.heapify(heap)\nheapq.heappush(heap, 2)\nsmallest = heapq.heappop(heap) # 1\n\nmax_heap = []\nheapq.heappush(max_heap, -10)\nlargest = -heapq.heappop(max_heap)",
    aliases: ["implement heap", "priority queue", "min heap", "max heap", "heapq", "实现堆", "优先队列"],
    complexity: "peek O(1) · push/pop O(log n) · heapify O(n)",
  },
  {
    id: "ds-trie", category: "Data Structures", title: "Trie / prefix tree", action: "实现 Trie 插入与搜索",
    description: "逐字符沿节点前进，适合前缀搜索、自动补全和字典匹配。", syntax: "insert(word) / search(word) / starts_with(prefix)",
    code: "class Trie:\n    def __init__(self):\n        self.children = {}\n        self.is_word = False\n\n    def insert(self, word):\n        node = self\n        for char in word:\n            node = node.children.setdefault(char, Trie())\n        node.is_word = True\n\n    def find(self, text):\n        node = self\n        for char in text:\n            if char not in node.children:\n                return None\n            node = node.children[char]\n        return node\n\n    def search(self, word):\n        node = self.find(word)\n        return bool(node and node.is_word)",
    aliases: ["implement trie", "prefix tree", "trie insert", "trie search", "实现字典树", "前缀树"],
    complexity: "insert/search O(L) · space O(total characters)",
  },
  {
    id: "ds-graph", category: "Data Structures", title: "Graph adjacency list", action: "实现 Graph / 邻接表",
    description: "邻接表只保存存在的边，适合稀疏图；无向边要添加两个方向。", syntax: "graph[node].append(neighbor)",
    code: "from collections import defaultdict\n\ngraph = defaultdict(list)\n\ndef add_edge(source, target, directed=False):\n    graph[source].append(target)\n    if not directed:\n        graph[target].append(source)\n\nadd_edge(\"A\", \"B\")\nadd_edge(\"A\", \"C\")",
    aliases: ["implement graph", "adjacency list", "directed graph", "undirected graph", "实现图", "邻接表"],
    complexity: "add edge O(1) · neighbors O(degree) · space O(V+E)",
  },
  {
    id: "ds-union-find", category: "Data Structures", title: "Union-Find / DSU", action: "实现并查集",
    description: "路径压缩 + 按大小合并，快速判断连通性并合并集合。", syntax: "find(x) / union(a, b)",
    code: "class UnionFind:\n    def __init__(self, n):\n        self.parent = list(range(n))\n        self.size = [1] * n\n\n    def find(self, x):\n        while x != self.parent[x]:\n            self.parent[x] = self.parent[self.parent[x]]\n            x = self.parent[x]\n        return x\n\n    def union(self, a, b):\n        ra, rb = self.find(a), self.find(b)\n        if ra == rb:\n            return False\n        if self.size[ra] < self.size[rb]:\n            ra, rb = rb, ra\n        self.parent[rb] = ra\n        self.size[ra] += self.size[rb]\n        return True",
    aliases: ["implement union find", "disjoint set union", "dsu", "path compression", "并查集", "连通性"],
    complexity: "amortized O(alpha(n)) per operation · space O(n)",
  },
  {
    id: "ds-lru-cache", category: "Data Structures", title: "LRU cache", action: "实现 LRU Cache",
    description: "OrderedDict 同时提供哈希查找和顺序维护；命中时移动到末尾，超量时弹出最旧项。", syntax: "move_to_end / popitem(last=False)",
    code: "from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity):\n        self.capacity = capacity\n        self.data = OrderedDict()\n\n    def get(self, key):\n        if key not in self.data:\n            return -1\n        self.data.move_to_end(key)\n        return self.data[key]\n\n    def put(self, key, value):\n        self.data[key] = value\n        self.data.move_to_end(key)\n        if len(self.data) > self.capacity:\n            self.data.popitem(last=False)",
    aliases: ["implement lru cache", "least recently used", "ordered dict cache", "实现缓存", "最近最少使用"],
    complexity: "get/put O(1) · space O(capacity)",
  },
  {
    id: "ds-segment-tree", category: "Data Structures", title: "Segment tree", action: "实现区间和 Segment Tree",
    description: "预处理数组后快速做区间查询和单点更新；这里使用迭代式 2n 存储。", syntax: "update(index, value) / query(left, right)",
    code: "class SegmentTree:\n    def __init__(self, values):\n        self.n = len(values)\n        self.tree = [0] * self.n + values[:]\n        for i in range(self.n - 1, 0, -1):\n            self.tree[i] = self.tree[2*i] + self.tree[2*i+1]\n\n    def update(self, index, value):\n        i = index + self.n\n        self.tree[i] = value\n        while i > 1:\n            i //= 2\n            self.tree[i] = self.tree[2*i] + self.tree[2*i+1]\n\n    def query(self, left, right):\n        total, left, right = 0, left + self.n, right + self.n\n        while left < right:\n            if left & 1: total += self.tree[left]; left += 1\n            if right & 1: right -= 1; total += self.tree[right]\n            left //= 2; right //= 2\n        return total",
    aliases: ["implement segment tree", "range sum query", "range query", "线段树", "区间和"],
    complexity: "build O(n) · update/query O(log n) · space O(n)",
  },
  {
    id: "ds-fenwick-tree", category: "Data Structures", title: "Fenwick tree / BIT", action: "实现 Binary Indexed Tree",
    description: "利用最低位 lowbit 累积前缀和，代码比 Segment Tree 更短。索引从 1 开始。", syntax: "add(index, delta) / prefix_sum(index)",
    code: "class FenwickTree:\n    def __init__(self, n):\n        self.tree = [0] * (n + 1)\n\n    def add(self, index, delta):\n        while index < len(self.tree):\n            self.tree[index] += delta\n            index += index & -index\n\n    def prefix_sum(self, index):\n        total = 0\n        while index > 0:\n            total += self.tree[index]\n            index -= index & -index\n        return total",
    aliases: ["implement fenwick tree", "binary indexed tree", "bit tree", "prefix sum updates", "树状数组", "动态前缀和"],
    complexity: "update/prefix O(log n) · space O(n)",
  },
  {
    id: "algo-binary-search", category: "Algorithms", title: "Binary search", action: "实现二分查找",
    description: "在有序数组中维护闭区间 [left, right]；每次排除一半。", syntax: "while left <= right: mid = (left + right) // 2",
    code: "def binary_search(values, target):\n    left, right = 0, len(values) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if values[mid] == target:\n            return mid\n        if values[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1",
    aliases: ["implement binary search", "binary search template", "二分查找", "有序数组查找"],
    complexity: "time O(log n) · space O(1)",
  },
  {
    id: "algo-rotated-binary-search", category: "Algorithms", title: "Search rotated array", action: "旋转数组二分查找",
    description: "每轮至少有一半仍然有序，判断 target 是否落在有序半边。", syntax: "identify sorted half, then discard the other half",
    code: "def search_rotated(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target: return mid\n        if nums[left] <= nums[mid]:\n            if nums[left] <= target < nums[mid]: right = mid - 1\n            else: left = mid + 1\n        else:\n            if nums[mid] < target <= nums[right]: left = mid + 1\n            else: right = mid - 1\n    return -1",
    aliases: ["rotated sorted array", "search rotated", "modified binary search", "旋转数组", "旋转二分"],
    complexity: "time O(log n) · space O(1)",
  },
  {
    id: "algo-bfs", category: "Algorithms", title: "Breadth-first search", action: "实现 Graph BFS / 广度优先",
    description: "队列逐层扩展；无权图中第一次到达节点就是最短边数。", syntax: "queue = deque([start]); while queue: node = popleft()",
    code: "from collections import deque\n\ndef bfs(graph, start):\n    queue = deque([start])\n    seen = {start}\n    order = []\n    while queue:\n        node = queue.popleft()\n        order.append(node)\n        for neighbor in graph[node]:\n            if neighbor not in seen:\n                seen.add(neighbor)\n                queue.append(neighbor)\n    return order",
    aliases: ["implement bfs", "breadth first search", "graph bfs", "level order", "广度优先搜索", "层序遍历"],
    complexity: "time O(V+E) · space O(V)",
  },
  {
    id: "algo-dfs", category: "Algorithms", title: "Depth-first search", action: "实现 Graph DFS / 深度优先",
    description: "沿一条路径走到底再回退；可递归，也可用显式 stack 避免递归深度限制。", syntax: "stack = [start]; while stack: node = stack.pop()",
    code: "def dfs(graph, start):\n    stack = [start]\n    seen = set()\n    order = []\n    while stack:\n        node = stack.pop()\n        if node in seen:\n            continue\n        seen.add(node)\n        order.append(node)\n        stack.extend(reversed(graph[node]))\n    return order",
    aliases: ["implement dfs", "depth first search", "graph dfs", "iterative dfs", "深度优先搜索"],
    complexity: "time O(V+E) · space O(V)",
  },
  {
    id: "algo-tree-traversal", category: "Algorithms", title: "Tree DFS traversals", action: "前序 / 中序 / 后序遍历",
    description: "递归函数相对 root 的访问位置决定 preorder、inorder、postorder。", syntax: "visit before / between / after recursive child calls",
    code: "def traversals(root):\n    preorder, inorder, postorder = [], [], []\n\n    def dfs(node):\n        if not node: return\n        preorder.append(node.value)\n        dfs(node.left)\n        inorder.append(node.value)\n        dfs(node.right)\n        postorder.append(node.value)\n\n    dfs(root)\n    return preorder, inorder, postorder",
    aliases: ["tree traversal", "preorder", "inorder", "postorder", "binary tree dfs", "前序遍历", "中序遍历", "后序遍历"],
    complexity: "time O(n) · recursion space O(h)",
  },
  {
    id: "algo-topological-sort", category: "Algorithms", title: "Topological sort / Kahn", action: "实现拓扑排序",
    description: "不断取入度为 0 的节点；结果不足 V 个说明有环。仅适用于有向无环图。", syntax: "indegree + queue of zero-indegree nodes",
    code: "from collections import deque\n\ndef topological_sort(graph):\n    indegree = {node: 0 for node in graph}\n    for neighbors in graph.values():\n        for node in neighbors:\n            indegree[node] = indegree.get(node, 0) + 1\n    queue = deque(node for node, degree in indegree.items() if degree == 0)\n    order = []\n    while queue:\n        node = queue.popleft()\n        order.append(node)\n        for neighbor in graph.get(node, []):\n            indegree[neighbor] -= 1\n            if indegree[neighbor] == 0: queue.append(neighbor)\n    return order if len(order) == len(indegree) else []",
    aliases: ["topological sort", "kahn algorithm", "course schedule", "dag ordering", "拓扑排序", "入度"],
    complexity: "time O(V+E) · space O(V)",
  },
  {
    id: "algo-dijkstra", category: "Algorithms", title: "Dijkstra shortest path", action: "实现非负权最短路",
    description: "最小堆每次确定当前最近节点；不能处理负权边。", syntax: "min_heap of (distance, node) + edge relaxation",
    code: "import heapq\n\ndef dijkstra(graph, start):\n    distance = {start: 0}\n    heap = [(0, start)]\n    while heap:\n        dist, node = heapq.heappop(heap)\n        if dist != distance[node]: continue\n        for neighbor, weight in graph[node]:\n            candidate = dist + weight\n            if candidate < distance.get(neighbor, float(\"inf\")):\n                distance[neighbor] = candidate\n                heapq.heappush(heap, (candidate, neighbor))\n    return distance",
    aliases: ["dijkstra", "shortest path", "weighted graph", "nonnegative edges", "最短路径", "迪杰斯特拉"],
    complexity: "time O((V+E) log V) · space O(V)",
  },
  {
    id: "algo-kruskal", category: "Algorithms", title: "Kruskal minimum spanning tree", action: "实现最小生成树 MST",
    description: "按边权从小到大尝试，用 Union-Find 跳过会形成环的边。", syntax: "sort edges + union endpoints",
    code: "def kruskal(n, edges):\n    uf = UnionFind(n)\n    total = 0\n    chosen = []\n    for weight, left, right in sorted(edges):\n        if uf.union(left, right):\n            total += weight\n            chosen.append((left, right, weight))\n            if len(chosen) == n - 1:\n                break\n    return total, chosen",
    aliases: ["kruskal", "minimum spanning tree", "mst", "union find graph", "最小生成树", "克鲁斯卡尔"],
    complexity: "time O(E log E) · space O(V)",
  },
  {
    id: "algo-merge-sort", category: "Algorithms", title: "Merge sort", action: "实现归并排序",
    description: "递归分半，再线性合并两个有序数组；稳定但需要额外空间。", syntax: "sort left + sort right + merge",
    code: "def merge_sort(values):\n    if len(values) <= 1: return values\n    mid = len(values) // 2\n    left = merge_sort(values[:mid])\n    right = merge_sort(values[mid:])\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]: result.append(left[i]); i += 1\n        else: result.append(right[j]); j += 1\n    return result + left[i:] + right[j:]",
    aliases: ["merge sort", "implement merge sort", "stable sort", "归并排序"],
    complexity: "time O(n log n) · space O(n)",
  },
  {
    id: "algo-quick-sort", category: "Algorithms", title: "Quick sort", action: "实现快速排序",
    description: "按 pivot 分区后递归；平均很快，但坏 pivot 会退化到 O(n²)。", syntax: "partition around pivot, then recurse",
    code: "def quick_sort(values):\n    if len(values) <= 1: return values\n    pivot = values[len(values) // 2]\n    lower = [value for value in values if value < pivot]\n    equal = [value for value in values if value == pivot]\n    higher = [value for value in values if value > pivot]\n    return quick_sort(lower) + equal + quick_sort(higher)",
    aliases: ["quick sort", "implement quicksort", "pivot partition", "快速排序", "分区排序"],
    complexity: "average O(n log n) · worst O(n²) · space O(n)",
  },
  {
    id: "algo-heap-sort", category: "Algorithms", title: "Heap sort", action: "实现堆排序",
    description: "先建堆，再依次弹出最小值；此简洁版本使用 O(n) 输出空间。", syntax: "heapify(values); repeatedly heappop",
    code: "import heapq\n\ndef heap_sort(values):\n    heap = values.copy()\n    heapq.heapify(heap)\n    return [heapq.heappop(heap) for _ in range(len(heap))]",
    aliases: ["heap sort", "implement heapsort", "sort with heap", "堆排序"],
    complexity: "time O(n log n) · extra space O(n)",
  },
  {
    id: "algo-two-pointers", category: "Algorithms", title: "Two pointers", action: "双指针查找配对",
    description: "有序数组两端向中间移动，根据当前结果单调排除不可能区域。", syntax: "left, right = 0, len(values)-1",
    code: "def two_sum_sorted(values, target):\n    left, right = 0, len(values) - 1\n    while left < right:\n        total = values[left] + values[right]\n        if total == target: return left, right\n        if total < target: left += 1\n        else: right -= 1\n    return None",
    aliases: ["two pointers", "two sum sorted", "left right pointers", "双指针", "左右指针"],
    complexity: "time O(n) · space O(1)",
  },
  {
    id: "algo-sliding-window", category: "Algorithms", title: "Sliding window", action: "可变长度滑动窗口",
    description: "右指针扩张，违反条件时移动左指针；避免重复计算每个子数组。", syntax: "for right: add; while invalid: remove left",
    code: "def longest_unique(text):\n    seen = set()\n    left = best = 0\n    for right, char in enumerate(text):\n        while char in seen:\n            seen.remove(text[left])\n            left += 1\n        seen.add(char)\n        best = max(best, right - left + 1)\n    return best",
    aliases: ["sliding window", "longest substring", "variable window", "滑动窗口", "无重复子串"],
    complexity: "time O(n) · space O(k)",
  },
  {
    id: "algo-prefix-sum", category: "Algorithms", title: "Prefix sum", action: "前缀和区间查询",
    description: "prefix[i] 保存前 i 个元素总和，任意半开区间 [left,right) 可 O(1) 查询。", syntax: "range_sum = prefix[right] - prefix[left]",
    code: "def build_prefix(values):\n    prefix = [0]\n    for value in values:\n        prefix.append(prefix[-1] + value)\n    return prefix\n\nvalues = [2, 4, 1, 3]\nprefix = build_prefix(values)\nleft, right = 1, 4\nrange_sum = prefix[right] - prefix[left] # 8",
    aliases: ["prefix sum", "range sum", "cumulative sum", "前缀和", "区间和"],
    complexity: "build O(n) · query O(1) · space O(n)",
  },
  {
    id: "algo-kadane", category: "Algorithms", title: "Kadane maximum subarray", action: "最大子数组和",
    description: "当前位置最优值只取决于“重新开始”还是“接到之前子数组”。", syntax: "current = max(value, current + value)",
    code: "def max_subarray(values):\n    current = best = values[0]\n    for value in values[1:]:\n        current = max(value, current + value)\n        best = max(best, current)\n    return best",
    aliases: ["kadane", "maximum subarray", "max subarray sum", "最大子数组", "连续子数组和"],
    complexity: "time O(n) · space O(1)",
  },
  {
    id: "algo-merge-intervals", category: "Algorithms", title: "Merge intervals", action: "合并重叠区间",
    description: "先按起点排序；当前区间与最后结果重叠时扩展终点，否则新增区间。", syntax: "sort by start, then compare with merged[-1]",
    code: "def merge_intervals(intervals):\n    merged = []\n    for start, end in sorted(intervals):\n        if not merged or start > merged[-1][1]:\n            merged.append([start, end])\n        else:\n            merged[-1][1] = max(merged[-1][1], end)\n    return merged",
    aliases: ["merge intervals", "overlapping intervals", "interval algorithm", "合并区间", "重叠区间"],
    complexity: "time O(n log n) · space O(n)",
  },
  {
    id: "algo-backtracking-subsets", category: "Algorithms", title: "Backtracking subsets", action: "回溯生成所有子集",
    description: "每个位置做“选择/不选择”；path 修改后递归，返回时撤销选择。", syntax: "choose -> recurse -> undo",
    code: "def subsets(values):\n    result, path = [], []\n\n    def backtrack(index):\n        if index == len(values):\n            result.append(path.copy())\n            return\n        backtrack(index + 1)\n        path.append(values[index])\n        backtrack(index + 1)\n        path.pop()\n\n    backtrack(0)\n    return result",
    aliases: ["backtracking", "generate subsets", "power set", "choose recurse undo", "回溯", "所有子集"],
    complexity: "time O(n·2^n) · output space O(n·2^n)",
  },
  {
    id: "algo-permutations", category: "Algorithms", title: "Backtracking permutations", action: "回溯生成全排列",
    description: "used 记录已选择位置；path 长度达到 n 时保存一个排列。", syntax: "for each unused value: choose -> recurse -> undo",
    code: "def permutations(values):\n    result, path = [], []\n    used = [False] * len(values)\n\n    def backtrack():\n        if len(path) == len(values):\n            result.append(path.copy())\n            return\n        for i, value in enumerate(values):\n            if used[i]: continue\n            used[i] = True; path.append(value)\n            backtrack()\n            path.pop(); used[i] = False\n\n    backtrack()\n    return result",
    aliases: ["permutations", "generate permutations", "backtracking permutation", "全排列", "排列组合"],
    complexity: "time O(n·n!) · output space O(n·n!)",
  },
  {
    id: "algo-monotonic-stack", category: "Algorithms", title: "Monotonic stack", action: "下一个更大元素",
    description: "栈中保留尚未找到答案的下标；新值更大时连续弹栈并结算。", syntax: "while stack and current > values[stack[-1]]: pop",
    code: "def next_greater(values):\n    answer = [-1] * len(values)\n    stack = []\n    for index, value in enumerate(values):\n        while stack and value > values[stack[-1]]:\n            previous = stack.pop()\n            answer[previous] = value\n        stack.append(index)\n    return answer",
    aliases: ["monotonic stack", "next greater element", "increasing stack", "单调栈", "下一个更大元素"],
    complexity: "time O(n) · space O(n)",
  },
  {
    id: "algo-dp-1d", category: "Algorithms", title: "1-D dynamic programming", action: "一维 DP / House Robber",
    description: "定义状态含义，再写转移。这里只需保留前两个状态，可压缩空间。", syntax: "current = max(previous, before_previous + value)",
    code: "def house_robber(values):\n    before_previous = previous = 0\n    for value in values:\n        current = max(previous, before_previous + value)\n        before_previous, previous = previous, current\n    return previous",
    aliases: ["1d dp", "dynamic programming", "house robber", "dp state transition", "一维动态规划", "状态转移"],
    complexity: "time O(n) · space O(1)",
  },
  {
    id: "algo-knapsack", category: "Algorithms", title: "0/1 knapsack", action: "背包 DP",
    description: "容量倒序更新，确保每件物品最多使用一次；正序会变成完全背包。", syntax: "for capacity descending: dp[c] = max(dp[c], dp[c-w] + value)",
    code: "def knapsack(weights, values, capacity):\n    dp = [0] * (capacity + 1)\n    for weight, value in zip(weights, values):\n        for current in range(capacity, weight - 1, -1):\n            dp[current] = max(dp[current], dp[current-weight] + value)\n    return dp[capacity]",
    aliases: ["0 1 knapsack", "knapsack dp", "背包问题", "容量动态规划"],
    complexity: "time O(items·capacity) · space O(capacity)",
  },
  {
    id: "algo-lcs", category: "Algorithms", title: "Longest common subsequence", action: "二维 DP / LCS",
    description: "dp[row][col] 表示两个前缀的最长公共子序列长度。", syntax: "match: diagonal+1; otherwise max(top, left)",
    code: "def lcs(left, right):\n    dp = [[0] * (len(right)+1) for _ in range(len(left)+1)]\n    for i, a in enumerate(left, start=1):\n        for j, b in enumerate(right, start=1):\n            if a == b:\n                dp[i][j] = dp[i-1][j-1] + 1\n            else:\n                dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n    return dp[-1][-1]",
    aliases: ["lcs", "longest common subsequence", "2d dp", "二维动态规划", "最长公共子序列"],
    complexity: "time O(mn) · space O(mn)",
  },
  {
    id: "algo-floyd-cycle", category: "Algorithms", title: "Floyd cycle detection", action: "快慢指针检测环",
    description: "slow 每次一步、fast 每次两步；有环时一定会相遇。", syntax: "slow = slow.next; fast = fast.next.next",
    code: "def has_cycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow is fast:\n            return True\n    return False",
    aliases: ["floyd cycle", "linked list cycle", "fast slow pointers", "cycle detection", "快慢指针", "链表环"],
    complexity: "time O(n) · space O(1)",
  },
  {
    id: "algo-binary-search-answer", category: "Algorithms", title: "Binary search the answer", action: "对答案空间二分",
    description: "当 can_finish(limit) 随 limit 单调变化时，查找第一个可行答案。", syntax: "if feasible(mid): right = mid else left = mid + 1",
    code: "def first_feasible(low, high, feasible):\n    while low < high:\n        mid = (low + high) // 2\n        if feasible(mid):\n            high = mid\n        else:\n            low = mid + 1\n    return low",
    aliases: ["binary search answer", "first feasible", "minimum capacity", "koko bananas", "答案二分", "最小可行值"],
    complexity: "time O(check·log range) · space depends on check",
  },
  {
    id: "algo-kmp", category: "Algorithms", title: "KMP string search", action: "实现字符串模式匹配",
    description: "LPS 表记录失败后可复用的最长前后缀，避免主串指针回退。", syntax: "build LPS, then scan text and pattern",
    code: "def kmp(text, pattern):\n    if not pattern: return 0\n    lps = [0] * len(pattern)\n    length = 0\n    for i in range(1, len(pattern)):\n        while length and pattern[i] != pattern[length]:\n            length = lps[length-1]\n        if pattern[i] == pattern[length]: length += 1\n        lps[i] = length\n    matched = 0\n    for i, char in enumerate(text):\n        while matched and char != pattern[matched]:\n            matched = lps[matched-1]\n        if char == pattern[matched]: matched += 1\n        if matched == len(pattern): return i - matched + 1\n    return -1",
    aliases: ["kmp", "knuth morris pratt", "substring search", "pattern matching", "字符串匹配", "前缀函数"],
    complexity: "time O(text + pattern) · space O(pattern)",
  },
  {
    id: "algo-greedy-intervals", category: "Algorithms", title: "Greedy interval scheduling", action: "贪心选择最多不重叠区间",
    description: "按结束时间排序，每次选择最早结束且不冲突的区间，给后续留下最大空间。", syntax: "sort by end; take interval when start >= previous_end",
    code: "def max_non_overlapping(intervals):\n    selected = []\n    previous_end = float(\"-inf\")\n    for start, end in sorted(intervals, key=lambda item: item[1]):\n        if start >= previous_end:\n            selected.append((start, end))\n            previous_end = end\n    return selected",
    aliases: ["greedy intervals", "interval scheduling", "activity selection", "non overlapping intervals", "贪心区间", "活动选择"],
    complexity: "time O(n log n) · space O(n) output",
  },
];
