// Learning content for the system-knowledge map.
//
// Two dimensions describe every resource instead of the old single `source`:
//   - kind:    what form the resource takes (DOC / COURSE / BOOK / ARTICLE / REPO)
//   - inDaily: whether it is already surfaced inside the Daily dashboard
//
// Every knowledge node answers three questions about the concept itself:
//   - what (是什么):   what it is / what it does
//   - why  (为什么):   why you need it / what problem it solves
//   - how  (怎么做的): the concrete mechanism — how it actually works
export type KnowledgeResourceKind = "DOC" | "COURSE" | "BOOK" | "ARTICLE" | "REPO";

export type KnowledgeLearningResource = {
  id: string;
  label: string;
  provider: string;
  url: string;
  kind: KnowledgeResourceKind;
  inDaily: boolean;
  note: string;
  noteZh: string;
};

export type KnowledgeNodeLearning = {
  what: string;
  whatZh: string;
  why: string;
  whyZh: string;
  how: string;
  howZh: string;
  resourceIds: string[];
};

export const knowledgeLearningResources: KnowledgeLearningResource[] = [
  { id: "how-web-works", label: "How the web works", provider: "MDN", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works", kind: "DOC", inDaily: false, note: "Browser, DNS, HTTP, and server in one request.", noteZh: "用一次请求串起浏览器、DNS、HTTP 与服务器。" },
  { id: "mdn-http", label: "HTTP", provider: "MDN", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP", kind: "DOC", inDaily: false, note: "Methods, status codes, headers, caching, cookies, and security.", noteZh: "方法、状态码、Header、缓存、Cookie 与安全。" },
  { id: "browser-work", label: "How browsers work", provider: "MDN", url: "https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/How_browsers_work", kind: "DOC", inDaily: false, note: "Navigation, parsing, layout, paint, and compositing.", noteZh: "导航、解析、布局、绘制与合成。" },
  { id: "mdn-html", label: "HTML reference", provider: "MDN", url: "https://developer.mozilla.org/en-US/docs/Web/HTML", kind: "DOC", inDaily: false, note: "Native elements, semantics, forms, and accessibility.", noteZh: "原生元素、语义、表单与可访问性。" },
  { id: "mdn-css", label: "CSS layout", provider: "MDN", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout", kind: "DOC", inDaily: false, note: "Normal flow, flexbox, grid, positioning, and responsive layout.", noteZh: "普通流、Flexbox、Grid、定位与响应式布局。" },
  { id: "mdn-js", label: "JavaScript Guide", provider: "MDN", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide", kind: "DOC", inDaily: true, note: "The language reference already linked in Daily.", noteZh: "Daily 已收录的 JavaScript 语言主参考。" },
  { id: "fcc-js", label: "JavaScript V9", provider: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/javascript-v9/", kind: "COURSE", inDaily: true, note: "Project-based JavaScript practice from foundations onward.", noteZh: "从基础开始的项目式 JavaScript 练习。" },
  { id: "ts-docs", label: "TypeScript Handbook", provider: "TypeScript", url: "https://www.typescriptlang.org/docs/handbook/intro.html", kind: "DOC", inDaily: true, note: "Types, narrowing, generics, and module contracts.", noteZh: "类型、收窄、泛型与模块契约。" },
  { id: "vite-docs", label: "Vite Guide", provider: "Vite", url: "https://vite.dev/guide/", kind: "DOC", inDaily: false, note: "Development server, modules, assets, environment, and builds.", noteZh: "开发服务器、模块、资源、环境变量与构建。" },
  { id: "npm-docs", label: "npm Docs", provider: "npm", url: "https://docs.npmjs.com/", kind: "DOC", inDaily: false, note: "Packages, scripts, dependency ranges, and publishing.", noteZh: "Package、Script、依赖版本与发布。" },
  { id: "react-learn", label: "Learn React", provider: "React", url: "https://react.dev/learn", kind: "DOC", inDaily: true, note: "The official component and state mental model.", noteZh: "官方组件与状态心智模型。" },
  { id: "fcc-frontend", label: "Front End Libraries V9", provider: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/front-end-development-libraries-v9/", kind: "COURSE", inDaily: true, note: "Practice React and modern frontend libraries.", noteZh: "练习 React 与现代前端库。" },
  { id: "react-thinking", label: "Thinking in React", provider: "React", url: "https://react.dev/learn/thinking-in-react", kind: "DOC", inDaily: false, note: "Derive component boundaries and state ownership from data flow.", noteZh: "从数据流推导组件边界与状态所有权。" },
  { id: "react-state", label: "Managing State", provider: "React", url: "https://react.dev/learn/managing-state", kind: "DOC", inDaily: false, note: "Structure, share, preserve, and reset UI state.", noteZh: "组织、共享、保留与重置 UI 状态。" },
  { id: "react-router", label: "React Router", provider: "React Router", url: "https://reactrouter.com/start/declarative/routing", kind: "DOC", inDaily: false, note: "Routes, nested layouts, params, and navigation.", noteZh: "路由、嵌套布局、参数与导航。" },
  { id: "tanstack-query", label: "TanStack Query", provider: "TanStack", url: "https://tanstack.com/query/latest/docs/framework/react/overview", kind: "DOC", inDaily: false, note: "Fetching, caching, invalidation, retries, and optimistic updates.", noteZh: "请求、缓存、失效、重试与乐观更新。" },
  { id: "mdn-a11y", label: "Accessibility", provider: "MDN", url: "https://developer.mozilla.org/en-US/docs/Web/Accessibility", kind: "DOC", inDaily: false, note: "Semantics, keyboard support, ARIA, vision, and motion.", noteZh: "语义、键盘、ARIA、视觉与动效需求。" },
  { id: "testing-library", label: "React Testing Library", provider: "Testing Library", url: "https://testing-library.com/docs/react-testing-library/intro/", kind: "DOC", inDaily: true, note: "Test interfaces through user-observable behavior.", noteZh: "通过用户可观察行为测试界面。" },
  { id: "fullstack-open", label: "Full Stack Open", provider: "University of Helsinki", url: "https://fullstackopen.com/en/", kind: "COURSE", inDaily: true, note: "React, APIs, testing, TypeScript, containers, and CI.", noteZh: "React、API、测试、TypeScript、容器与 CI。" },
  { id: "node-learn", label: "Introduction to Node.js", provider: "Node.js", url: "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs", kind: "DOC", inDaily: false, note: "Server JavaScript, event loop, modules, and process behavior.", noteZh: "服务端 JavaScript、事件循环、模块与进程行为。" },
  { id: "python-tutorial", label: "Python Tutorial", provider: "Python", url: "https://docs.python.org/3/tutorial/", kind: "DOC", inDaily: false, note: "Language, modules, errors, classes, and standard library.", noteZh: "语言、模块、错误、类与标准库。" },
  { id: "python-packaging", label: "Packaging Python Projects", provider: "PyPA", url: "https://packaging.python.org/en/latest/tutorials/packaging-projects/", kind: "DOC", inDaily: true, note: "Turn Python code into a typed, installable project.", noteZh: "把 Python 代码变成可安装、可复现的项目。" },
  { id: "openapi", label: "OpenAPI Specification", provider: "OpenAPI Initiative", url: "https://spec.openapis.org/oas/latest.html", kind: "DOC", inDaily: false, note: "Describe request, response, errors, schemas, and compatibility.", noteZh: "描述请求、响应、错误、Schema 与兼容性。" },
  { id: "fastapi", label: "FastAPI Tutorial", provider: "FastAPI", url: "https://fastapi.tiangolo.com/tutorial/", kind: "DOC", inDaily: true, note: "Validation, dependencies, databases, tests, and deployment.", noteZh: "验证、依赖注入、数据库、测试与部署。" },
  { id: "express", label: "Express Getting Started", provider: "Express", url: "https://expressjs.com/en/starter/installing.html", kind: "DOC", inDaily: false, note: "Minimal Node routing and middleware fundamentals.", noteZh: "最小化掌握 Node Route 与 Middleware。" },
  { id: "fcc-backend", label: "Back End Development and APIs", provider: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/back-end-development-and-apis/", kind: "COURSE", inDaily: true, note: "Node, Express, APIs, middleware, and persistence projects.", noteZh: "Node、Express、API、Middleware 与持久化项目。" },
  { id: "cosmic-python", label: "Architecture Patterns with Python", provider: "Cosmic Python", url: "https://www.cosmicpython.com/book/preface", kind: "BOOK", inDaily: true, note: "Repository, service layer, unit of work, and message bus.", noteZh: "Repository、Service Layer、Unit of Work 与 Message Bus。" },
  { id: "owasp", label: "OWASP Top 10", provider: "OWASP", url: "https://owasp.org/www-project-top-ten/", kind: "DOC", inDaily: true, note: "The most important web application security failure classes.", noteZh: "最重要的 Web 应用安全失败类型。" },
  { id: "oauth", label: "OAuth 2.0", provider: "IETF", url: "https://www.rfc-editor.org/rfc/rfc6749", kind: "DOC", inDaily: false, note: "Delegated authorization roles, grants, tokens, and boundaries.", noteZh: "委托授权角色、Grant、Token 与边界。" },
  { id: "celery", label: "Celery First Steps", provider: "Celery", url: "https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html", kind: "DOC", inDaily: false, note: "Queues, workers, retries, results, and background tasks.", noteZh: "Queue、Worker、Retry、Result 与后台任务。" },
  { id: "pytest", label: "pytest Getting Started", provider: "pytest", url: "https://docs.pytest.org/en/stable/getting-started.html", kind: "DOC", inDaily: true, note: "Fixtures, assertions, parametrization, and test discovery.", noteZh: "Fixture、Assertion、参数化与测试发现。" },
  { id: "fastapi-tests", label: "Testing FastAPI", provider: "FastAPI", url: "https://fastapi.tiangolo.com/tutorial/testing/", kind: "DOC", inDaily: false, note: "Exercise real API routes with a test client.", noteZh: "用 Test Client 验证真实 API Route。" },
  { id: "fcc-db", label: "Relational Database", provider: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/relational-database/", kind: "COURSE", inDaily: true, note: "SQL, PostgreSQL, shell, Git, and database projects.", noteZh: "SQL、PostgreSQL、Shell、Git 与数据库项目。" },
  { id: "postgres-tutorial", label: "PostgreSQL Tutorial", provider: "PostgreSQL", url: "https://www.postgresql.org/docs/current/tutorial.html", kind: "DOC", inDaily: false, note: "Tables, queries, joins, aggregates, transactions, and windows.", noteZh: "表、查询、Join、聚合、事务与 Window。" },
  { id: "postgres-ddl", label: "Data Definition", provider: "PostgreSQL", url: "https://www.postgresql.org/docs/current/ddl.html", kind: "DOC", inDaily: false, note: "Schemas, constraints, defaults, privileges, and partitioning.", noteZh: "Schema、Constraint、Default、权限与分区。" },
  { id: "alembic", label: "Alembic Tutorial", provider: "SQLAlchemy", url: "https://alembic.sqlalchemy.org/en/latest/tutorial.html", kind: "DOC", inDaily: false, note: "Version and apply database schema changes.", noteZh: "版本化并执行数据库 Schema 变化。" },
  { id: "redis", label: "Redis Documentation", provider: "Redis", url: "https://redis.io/docs/latest/", kind: "DOC", inDaily: false, note: "Data types, expiration, persistence, clients, and operations.", noteZh: "数据类型、过期、持久化、客户端与运维。" },
  { id: "postgres-search", label: "Full Text Search", provider: "PostgreSQL", url: "https://www.postgresql.org/docs/current/textsearch.html", kind: "DOC", inDaily: false, note: "Search documents with ranking and indexes inside PostgreSQL.", noteZh: "在 PostgreSQL 中用排序和索引搜索文档。" },
  { id: "pgvector", label: "pgvector", provider: "pgvector", url: "https://github.com/pgvector/pgvector", kind: "REPO", inDaily: false, note: "Store embeddings and run exact or approximate nearest-neighbor search.", noteZh: "存储 Embedding 并进行精确或近似相似度搜索。" },
  { id: "s3", label: "Amazon S3 User Guide", provider: "AWS", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html", kind: "DOC", inDaily: false, note: "Buckets, objects, presigned URLs, permissions, and lifecycle.", noteZh: "Bucket、Object、预签名 URL、权限与生命周期。" },
  { id: "linux-process", label: "proc filesystem", provider: "Linux man-pages", url: "https://man7.org/linux/man-pages/man5/proc.5.html", kind: "DOC", inDaily: false, note: "Inspect running processes, files, memory, and kernel state.", noteZh: "检查运行进程、文件、内存与 Kernel 状态。" },
  { id: "networking-guide", label: "Networking Fundamentals", provider: "Cloudflare", url: "https://www.cloudflare.com/learning/network-layer/what-is-a-computer-network/", kind: "ARTICLE", inDaily: false, note: "Packets, routing, protocols, latency, and network layers.", noteZh: "Packet、Routing、Protocol、Latency 与网络层。" },
  { id: "nginx-balancing", label: "HTTP Load Balancing", provider: "NGINX", url: "https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/", kind: "DOC", inDaily: false, note: "Distribute requests, configure health, and choose algorithms.", noteZh: "分发请求、配置健康检查并选择算法。" },
  { id: "docker", label: "Docker Get Started", provider: "Docker", url: "https://docs.docker.com/get-started/", kind: "DOC", inDaily: false, note: "Images, containers, Dockerfiles, volumes, and multi-container apps.", noteZh: "Image、Container、Dockerfile、Volume 与多容器应用。" },
  { id: "github-actions", label: "Build and test Python", provider: "GitHub Actions", url: "https://docs.github.com/en/actions/tutorials/build-and-test-code/python", kind: "DOC", inDaily: true, note: "Automate installation, tests, linting, and builds on every push.", noteZh: "每次 Push 自动安装、测试、Lint 与 Build。" },
  { id: "otel", label: "OpenTelemetry Docs", provider: "OpenTelemetry", url: "https://opentelemetry.io/docs/", kind: "DOC", inDaily: false, note: "Connect traces, metrics, logs, context, and collectors.", noteZh: "连接 Trace、Metric、Log、Context 与 Collector。" },
  { id: "sre-book", label: "Site Reliability Engineering", provider: "Google", url: "https://sre.google/sre-book/table-of-contents/", kind: "BOOK", inDaily: true, note: "SLIs, SLOs, alerting, overload, and reliable operations.", noteZh: "SLI、SLO、告警、过载与可靠运维。" },
  { id: "ddia", label: "Designing Data-Intensive Applications", provider: "Martin Kleppmann", url: "https://dataintensive.net/", kind: "BOOK", inDaily: true, note: "Replication, partitioning, transactions, streams, and tradeoffs.", noteZh: "复制、分区、事务、流与设计取舍。" },
  { id: "mit-distributed", label: "MIT 6.5840", provider: "MIT", url: "https://pdos.csail.mit.edu/6.824/", kind: "COURSE", inDaily: true, note: "Labs and lectures on replication, Raft, and fault tolerance.", noteZh: "复制、Raft 与容错的课程和实验。" },
  { id: "kafka", label: "Apache Kafka Documentation", provider: "Apache Kafka", url: "https://kafka.apache.org/documentation/", kind: "DOC", inDaily: false, note: "Topics, partitions, consumer groups, delivery, and replay.", noteZh: "Topic、Partition、Consumer Group、投递与重放。" },
  { id: "model-api", label: "API Reference", provider: "OpenAI", url: "https://platform.openai.com/docs/api-reference/introduction", kind: "DOC", inDaily: false, note: "Model requests, responses, errors, limits, and streaming.", noteZh: "模型请求、响应、错误、限制与 Streaming。" },
  { id: "effective-agents", label: "Building Effective Agents", provider: "Anthropic", url: "https://www.anthropic.com/research/building-effective-agents", kind: "ARTICLE", inDaily: false, note: "Workflows, agents, tools, loops, and when simplicity wins.", noteZh: "Workflow、Agent、Tool、Loop，以及何时应保持简单。" },
  { id: "structured-outputs", label: "Structured Outputs", provider: "OpenAI", url: "https://platform.openai.com/docs/guides/structured-outputs", kind: "DOC", inDaily: false, note: "Constrain model output with a validated JSON schema.", noteZh: "用经过验证的 JSON Schema 约束模型输出。" },
  { id: "function-calling", label: "Function Calling", provider: "OpenAI", url: "https://platform.openai.com/docs/guides/function-calling", kind: "DOC", inDaily: false, note: "Define tools, validate arguments, execute, and return results.", noteZh: "定义工具、验证参数、执行并返回结果。" },
  { id: "mcp-docs", label: "Model Context Protocol", provider: "MCP", url: "https://modelcontextprotocol.io/docs/getting-started/intro", kind: "DOC", inDaily: false, note: "Clients, servers, tools, resources, prompts, and transports.", noteZh: "Client、Server、Tool、Resource、Prompt 与 Transport。" },
  { id: "nist-ai-rmf", label: "AI Risk Management Framework", provider: "NIST", url: "https://www.nist.gov/itl/ai-risk-management-framework", kind: "DOC", inDaily: false, note: "Govern, map, measure, and manage AI risk.", noteZh: "治理、映射、衡量与管理 AI 风险。" },
  { id: "evals", label: "Evaluation Best Practices", provider: "OpenAI", url: "https://platform.openai.com/docs/guides/evaluation-best-practices", kind: "DOC", inDaily: false, note: "Task sets, rubrics, graders, regression testing, and iteration.", noteZh: "任务集、Rubric、Grader、回归测试与迭代。" },
  { id: "pi-web", label: "Pi Web Source", provider: "agegr · MIT", url: "https://github.com/agegr/pi-web", kind: "REPO", inDaily: true, note: "The local web workspace already integrated into Daily.", noteZh: "Daily 已整合的本地 Pi Web Workspace。" },
  { id: "pi-agent", label: "Pi Coding Agent", provider: "pi-mono", url: "https://github.com/badlogic/pi-mono/tree/main/packages/coding-agent", kind: "REPO", inDaily: false, note: "Sessions, providers, tools, extensions, and the coding-agent runtime.", noteZh: "Session、Provider、Tool、Extension 与 Coding Agent Runtime。" },
  { id: "openworker", label: "OpenWorker", provider: "Andrew Ng", url: "https://github.com/andrewyng/openworker", kind: "REPO", inDaily: true, note: "A local-first AI coworker architecture reference.", noteZh: "本地优先 AI Coworker 的架构参考。" },
  { id: "openwork", label: "OpenWork", provider: "different-ai", url: "https://github.com/different-ai/openwork", kind: "REPO", inDaily: true, note: "Desktop workflows, MCP, reusable skills, and human control.", noteZh: "桌面 Workflow、MCP、可复用 Skill 与人类控制。" },
];

export const knowledgeLearningResourceById = new Map(
  knowledgeLearningResources.map((resource) => [resource.id, resource]),
);

export const knowledgeNodeLearning: Record<string, KnowledgeNodeLearning> = {
  internet: {
    what: "The internet is a network of networks that gives every machine an address and moves packets between them; DNS translates human names into those addresses.",
    whatZh: "互联网是「网络的网络」，为每台机器分配地址并在它们之间传输数据包；DNS 把人类可读的名字翻译成这些地址。",
    why: "Programs reference servers by name, but packets can only travel to numeric addresses, so name resolution and routing are what make any connection possible.",
    whyZh: "程序用名字引用服务器，但数据包只能发往数字地址，所以域名解析和路由是任何连接得以建立的前提。",
    how: "A name is looked up through DNS to an IP address, packets are routed hop by hop across networks to that IP, and only then can a transport connection begin.",
    howZh: "名字先经 DNS 解析成 IP 地址，数据包再逐跳路由穿过网络到达该 IP，之后传输层连接才能开始。",
    resourceIds: ["how-web-works", "networking-guide"],
  },
  http: {
    what: "HTTP is the request/response protocol of the web, defining methods, status codes, headers, and caching; TLS wraps it in encryption and identity.",
    whatZh: "HTTP 是 Web 的请求/响应协议，定义方法、状态码、Header 和缓存；TLS 为其加上加密与身份验证。",
    why: "It is the shared language every client and server use to exchange data, so understanding it prevents whole classes of caching, state, and security bugs.",
    whyZh: "它是所有客户端和服务器交换数据的共同语言，理解它能避免一整类缓存、状态和安全 bug。",
    how: "A client sends a method, path, headers, and body; the server replies with a status code, headers, and body, while TLS negotiates keys before anything is sent in clear.",
    howZh: "客户端发送方法、路径、Header 和 Body；服务器回复状态码、Header 和 Body，而 TLS 在任何明文发送前先协商密钥。",
    resourceIds: ["mdn-http", "how-web-works"],
  },
  browser: {
    what: "The browser is the runtime that fetches documents, parses HTML and CSS, runs JavaScript, paints pixels, and enforces the web security model.",
    whatZh: "浏览器是获取文档、解析 HTML 与 CSS、运行 JavaScript、绘制像素并强制 Web 安全模型的运行时。",
    why: "Every web app ultimately runs inside it, so rendering, events, storage, and performance are all governed by how the browser processes a page.",
    whyZh: "每个 Web 应用最终都在其中运行，所以渲染、事件、存储和性能都由浏览器处理页面的方式决定。",
    how: "It parses HTML into a DOM and CSS into a CSSOM, computes layout, paints and composites layers, then runs JavaScript that reacts to events and mutates the DOM.",
    howZh: "它把 HTML 解析成 DOM、把 CSS 解析成 CSSOM，计算布局，绘制并合成图层，再运行响应事件、修改 DOM 的 JavaScript。",
    resourceIds: ["browser-work", "how-web-works"],
  },
  html: {
    what: "HTML is the markup language that describes a document's meaning and structure — headings, lists, links, forms, and interactive controls.",
    whatZh: "HTML 是描述文档含义与结构的标记语言——标题、列表、链接、表单和交互控件。",
    why: "Using the right elements gives you accessibility, keyboard support, forms, and SEO for free, before any JavaScript is written.",
    whyZh: "使用正确的元素能在写任何 JavaScript 之前，免费获得可访问性、键盘支持、表单和 SEO。",
    how: "You describe content with semantic tags like nav, button, and label, and the browser gives each its built-in behavior, roles, and default interactions.",
    howZh: "你用 nav、button、label 等语义标签描述内容，浏览器为每个元素提供内建行为、角色和默认交互。",
    resourceIds: ["mdn-html", "mdn-a11y"],
  },
  css: {
    what: "CSS is the language that controls visual presentation — layout, spacing, color, typography, responsiveness, and interaction states.",
    whatZh: "CSS 是控制视觉呈现的语言——布局、间距、颜色、排版、响应式和交互状态。",
    why: "The same markup must stay usable across screen sizes, content lengths, and input modes, and CSS is what makes that adaptation possible.",
    whyZh: "同一份标记必须在不同屏幕尺寸、内容长度和输入方式下都可用，而 CSS 正是实现这种适配的手段。",
    how: "Selectors match elements and apply rules; flexbox and grid arrange boxes, media queries adapt to the viewport, and pseudo-classes style focus and hover states.",
    howZh: "选择器匹配元素并应用规则；Flexbox 和 Grid 排列盒子，媒体查询适配视口，伪类为 focus、hover 等状态设置样式。",
    resourceIds: ["mdn-css", "mdn-a11y"],
  },
  javascript: {
    what: "JavaScript is the programming language of the web, expressing behavior through functions, objects, closures, promises, and an event loop.",
    whatZh: "JavaScript 是 Web 的编程语言，通过函数、对象、闭包、Promise 和事件循环表达行为。",
    why: "It is the only language browsers run natively and it underlies every frontend framework, so its core semantics show up everywhere.",
    whyZh: "它是浏览器唯一原生运行的语言，也是每个前端框架的底层，所以它的核心语义无处不在。",
    how: "Code runs single-threaded on an event loop; synchronous work runs to completion while async callbacks, promises, and timers are queued and resolved later.",
    howZh: "代码在事件循环上单线程运行；同步工作一次执行完，异步回调、Promise 和定时器则被排队并稍后解决。",
    resourceIds: ["fcc-js", "mdn-js"],
  },
  typescript: {
    what: "TypeScript is JavaScript with a static type system that describes the shape of values and checks them before the code runs.",
    whatZh: "TypeScript 是带静态类型系统的 JavaScript，用来描述值的结构并在代码运行前检查它们。",
    why: "Types make interfaces between modules explicit and turn many runtime mistakes into compile-time errors, which keeps large codebases changeable.",
    whyZh: "类型让模块间的接口显式，把许多运行时错误变成编译期错误，从而让大型代码库保持可改动。",
    how: "You annotate values and functions, the compiler infers and checks types, narrows unions, and reports mismatches, then erases all of it to plain JavaScript.",
    howZh: "你为值和函数标注类型，编译器推断并检查类型、收窄联合类型、报告不匹配，最后把这些全部擦除成纯 JavaScript。",
    resourceIds: ["ts-docs", "fullstack-open"],
  },
  "build-tools": {
    what: "Build tools resolve modules, transform source such as TSX, bundle assets, and provide a fast development feedback loop.",
    whatZh: "构建工具解析模块、转换源码（如 TSX）、打包资源，并提供快速的开发反馈循环。",
    why: "Browsers cannot run TypeScript or bare module graphs directly, so tooling is what turns source into something runnable and shippable.",
    whyZh: "浏览器无法直接运行 TypeScript 或裸模块图，所以工具链是把源码变成可运行、可交付产物的关键。",
    how: "A tool like Vite resolves imports, compiles source, serves modules with hot reload in development, and emits minified, hashed bundles for production.",
    howZh: "像 Vite 这样的工具解析 Import、编译源码，在开发时以热更新提供模块，并为生产输出经过压缩、带 Hash 的包。",
    resourceIds: ["vite-docs", "npm-docs"],
  },
  react: {
    what: "React is a library that maps application state to a tree of components and keeps the rendered UI in sync as that state changes.",
    whatZh: "React 是一个把应用状态映射到组件树、并在状态变化时保持渲染 UI 同步的库。",
    why: "It lets you compose interfaces from reusable pieces and describe UI as a function of state instead of manually mutating the DOM.",
    whyZh: "它让你用可复用的部件组合界面，把 UI 描述为状态的函数，而不是手动修改 DOM。",
    how: "You return elements from components; when state changes React re-renders, diffs the result against the previous tree, and updates only what changed.",
    howZh: "你从组件返回元素；状态变化时 React 重新渲染，把结果与上一棵树做 Diff，只更新发生变化的部分。",
    resourceIds: ["react-learn", "fcc-frontend"],
  },
  components: {
    what: "Components are self-contained UI units with explicit inputs (props) and behavior that can be composed and reused.",
    whatZh: "组件是自包含的 UI 单元，具有显式输入（props）和可组合、可复用的行为。",
    why: "Clear component boundaries reduce coupling and make interfaces easier to reason about, test, and change one piece at a time.",
    whyZh: "清晰的组件边界降低耦合，让界面更容易推理、测试和逐块修改。",
    how: "You split a UI by responsibility, pass data down through props, lift shared state to a common parent, and give each component one reason to change.",
    howZh: "你按职责拆分 UI，通过 props 向下传数据，把共享状态提升到共同父级，让每个组件只有一个变化原因。",
    resourceIds: ["react-thinking", "react-learn"],
  },
  state: {
    what: "Client state is the transient, in-memory data an interface holds while a user interacts with it — selections, inputs, toggles.",
    whatZh: "Client State 是界面在用户交互时持有的临时内存数据——选中项、输入、开关。",
    why: "Most UI bugs come from state that is duplicated, stale, or owned by the wrong place, so classifying state correctly prevents them.",
    whyZh: "多数 UI bug 来自被复制、过期或归错位置的状态，所以正确分类状态能提前避免它们。",
    how: "For each value you decide whether it is local, shared, derived from other state, stored in the URL, or owned by the server, and keep a single source of truth.",
    howZh: "你为每个值判断它是本地的、共享的、由其他状态派生的、存在 URL 里的，还是归服务器所有，并保持单一事实来源。",
    resourceIds: ["react-state", "react-thinking"],
  },
  routing: {
    what: "Routing maps URLs to screens and makes navigation between them shareable, bookmarkable, and recoverable.",
    whatZh: "路由把 URL 映射到界面，让它们之间的导航可分享、可收藏、可恢复。",
    why: "The URL is durable application state; treating it as such means refresh, back, and deep links all work correctly.",
    whyZh: "URL 是持久的应用状态；把它当作状态对待，刷新、后退和深链就都能正确工作。",
    how: "A router matches the current URL against defined routes, renders the matching screen (often with nested layouts and params), and updates history on navigation.",
    howZh: "路由器把当前 URL 与定义好的路由匹配，渲染对应界面（常带嵌套布局和参数），并在导航时更新历史记录。",
    resourceIds: ["react-router", "mdn-http"],
  },
  "server-state": {
    what: "Server state is remote data owned by a backend that a client fetches, caches, and must keep synchronized.",
    whatZh: "Server State 是由后端拥有、客户端获取、缓存并需保持同步的远程数据。",
    why: "Remote data has latency and can change without the client knowing, so treating it like local state produces stale and inconsistent UI.",
    whyZh: "远程数据有延迟且可能在客户端不知情时变化，所以把它当本地状态会导致 UI 过期、不一致。",
    how: "A data layer fetches on demand, caches responses, shows loading and error states, refetches or invalidates when data changes, and can update optimistically then roll back.",
    howZh: "数据层按需获取、缓存响应、展示 Loading 和 Error 状态，在数据变化时重新获取或失效，并可乐观更新后回滚。",
    resourceIds: ["tanstack-query", "fullstack-open"],
  },
  accessibility: {
    what: "Accessibility is building software that works across keyboard, screen reader, low vision, and reduced-motion needs.",
    whatZh: "可访问性是让软件能在键盘、读屏、低视力和减少动效等需求下都可用。",
    why: "It is part of correctness — some users can only operate an interface this way — and the structure it demands usually improves usability for everyone.",
    whyZh: "它是正确性的一部分——有些用户只能这样操作界面——而它要求的结构通常对所有人都提升可用性。",
    how: "You use semantic elements, ensure everything is reachable and operable by keyboard, add ARIA only where native semantics fall short, and test the accessibility tree.",
    howZh: "你使用语义元素，确保一切都能被键盘触达和操作，仅在原生语义不足时补 ARIA，并检查可访问性树。",
    resourceIds: ["mdn-a11y", "mdn-html"],
  },
  "frontend-testing": {
    what: "Frontend testing verifies the user-observable behavior of an interface — what a user can see and do — rather than internal implementation.",
    whatZh: "前端测试验证界面用户可观察的行为——用户能看到和做到什么——而不是内部实现。",
    why: "Tests give you confidence to refactor UI without breaking behavior, and asserting on behavior rather than internals keeps them from freezing the implementation.",
    whyZh: "测试让你能重构 UI 而不破坏行为，而断言行为（而非内部实现）能避免测试冻结实现。",
    how: "A test renders a component or flow, simulates user actions like clicks and typing, and asserts on the resulting visible output at unit, integration, or browser level.",
    howZh: "测试渲染组件或流程，模拟点击、输入等用户操作，并在单元、集成或浏览器层面断言产生的可见输出。",
    resourceIds: ["testing-library", "fullstack-open"],
  },
  "node-runtime": {
    what: "Node.js is a runtime that executes JavaScript outside the browser, on the server, with event-driven, non-blocking I/O.",
    whatZh: "Node.js 是在浏览器之外、于服务器上执行 JavaScript 的运行时，采用事件驱动、非阻塞的 I/O。",
    why: "It lets one language cover both client and server and handle many concurrent connections efficiently, though CPU-heavy work still needs care.",
    whyZh: "它让一种语言同时覆盖客户端和服务器，并高效处理大量并发连接，不过 CPU 密集工作仍需注意。",
    how: "A single-threaded event loop dispatches non-blocking I/O and runs callbacks as results arrive; CPU-bound work is offloaded to worker threads or separate processes.",
    howZh: "单线程事件循环调度非阻塞 I/O，并在结果到达时运行回调；CPU 密集工作被交给 Worker 线程或独立进程。",
    resourceIds: ["node-learn", "fcc-backend"],
  },
  python: {
    what: "Python is a high-level, dynamically typed language with a broad ecosystem for backend services, automation, data, and AI.",
    whatZh: "Python 是一门高级、动态类型语言，拥有覆盖后端服务、自动化、数据和 AI 的广泛生态。",
    why: "Its readability and libraries make it fast to express logic, while optional type hints and tests add the discipline larger systems need.",
    whyZh: "它的可读性和库让表达逻辑很快，而可选的类型提示和测试为更大的系统补上所需的纪律。",
    how: "You write functions, classes, and modules, pull packages from a rich ecosystem, add type hints checked by tools, and verify behavior with tests.",
    howZh: "你编写函数、类和模块，使用丰富生态中的包，加入由工具检查的类型提示，并用测试验证行为。",
    resourceIds: ["python-tutorial", "python-packaging"],
  },
  "api-contract": {
    what: "An API contract is the explicit agreement between a client and server about inputs, outputs, errors, identity, and compatibility.",
    whatZh: "API 契约是客户端与服务器之间关于输入、输出、错误、身份和兼容性的显式约定。",
    why: "A stable contract lets both sides evolve independently, and documenting every success and failure shape prevents integration surprises.",
    whyZh: "稳定的契约让双方能各自演进，而记录每种成功和失败形态能避免集成时的意外。",
    how: "You specify each endpoint's method, request schema, response schema, status codes, and error shapes — often in OpenAPI — and both sides code against it.",
    howZh: "你为每个端点指定方法、请求 Schema、响应 Schema、状态码和错误形态——常用 OpenAPI——双方都按它编码。",
    resourceIds: ["openapi", "fastapi"],
  },
  "backend-framework": {
    what: "A backend framework like FastAPI or Express maps incoming transport requests into validated calls into your application code.",
    whatZh: "FastAPI、Express 这类后端框架把进入的传输请求映射成对应用代码的已验证调用。",
    why: "It removes repetitive protocol handling — routing, parsing, serialization — so you don't rewrite HTTP plumbing for every endpoint.",
    whyZh: "它消除重复的协议处理——路由、解析、序列化——让你不必为每个端点重写 HTTP 管道。",
    how: "You declare routes and their expected inputs; the framework parses and validates the request, injects dependencies, calls your handler, and serializes the response.",
    howZh: "你声明路由及其期望输入；框架解析并验证请求、注入依赖、调用你的处理函数，并序列化响应。",
    resourceIds: ["fastapi", "express"],
  },
  "service-layer": {
    what: "The service layer holds an application's business rules, coordinating use cases independently of HTTP and storage.",
    whatZh: "Service Layer 承载应用的业务规则，独立于 HTTP 和存储来协调用例。",
    why: "Separating rules from transport and persistence makes use cases testable and stops routes or database models from absorbing all the logic.",
    whyZh: "把规则与传输和持久化分开，能让用例可测试，并阻止 Route 或数据库模型吸收所有逻辑。",
    how: "A service function takes domain inputs, enforces prerequisites and invariants, calls repositories to read and write, and returns a result with no knowledge of HTTP.",
    howZh: "Service 函数接收领域输入，执行前置条件和不变量，调用 Repository 读写，并返回一个不了解 HTTP 的结果。",
    resourceIds: ["cosmic-python", "fullstack-open"],
  },
  auth: {
    what: "Identity and authorization establish who a caller is and separately decide which operations and data they are allowed to touch.",
    whatZh: "身份与授权确立调用者是谁，并单独决定他们被允许操作哪些操作和数据。",
    why: "Authentication alone is not enough — without per-object authorization, one authenticated user can still read or modify another's data.",
    whyZh: "只有认证还不够——没有针对每个对象的授权，一个已认证用户仍能读取或修改他人的数据。",
    how: "A session or token proves identity on each request, then an authorization check compares that identity against the resource's owner or required role before acting.",
    howZh: "Session 或 Token 在每次请求时证明身份，随后授权检查在执行前把该身份与资源的所有者或所需角色比对。",
    resourceIds: ["owasp", "oauth"],
  },
  "background-jobs": {
    what: "Background jobs move slow, retryable, or scheduled work out of the request path so responses stay fast.",
    whatZh: "后台任务把缓慢、可重试或定时的工作移出请求路径，使响应保持快速。",
    why: "Some work is too slow or unreliable to run inline, and doing it in the background needs idempotency, retries, and visibility, not just a queue.",
    whyZh: "有些工作太慢或不可靠，不能内联执行，而在后台完成它需要幂等、重试和可见性，而不只是一个队列。",
    how: "A request enqueues a job and returns immediately; a worker picks it up, retries with backoff on failure, records progress, and routes exhausted jobs to a dead-letter path.",
    howZh: "请求把任务入队并立即返回；Worker 取出任务，失败时用退避重试，记录进度，并把耗尽重试的任务送到死信路径。",
    resourceIds: ["celery", "cosmic-python"],
  },
  "backend-testing": {
    what: "Backend testing verifies business rules, integration boundaries, and failure behavior of server-side code.",
    whatZh: "后端测试验证服务端代码的业务规则、集成边界和失败行为。",
    why: "Fast tests on rules plus a few real integration tests give more reliable confidence than mocking every dependency.",
    whyZh: "对规则的快速测试加上少量真实集成测试，比 Mock 每个依赖能提供更可靠的信心。",
    how: "Unit tests exercise service rules in isolation, repository tests run against a real database, and a few end-to-end tests verify validation and serialization through the API.",
    howZh: "单元测试隔离地验证 Service 规则，Repository 测试对真实数据库运行，少量端到端测试通过 API 验证校验与序列化。",
    resourceIds: ["pytest", "fastapi-tests"],
  },
  sql: {
    what: "SQL is a declarative language for querying and transforming relational data — selecting, joining, filtering, and aggregating.",
    whatZh: "SQL 是查询和转换关系数据的声明式语言——选择、连接、过滤和聚合。",
    why: "Relational databases are everywhere, and an ORM does not remove joins, transactions, query plans, or the need to reason about cardinality.",
    whyZh: "关系数据库无处不在，而 ORM 不会消除 Join、事务、查询计划，也不消除对基数的推理。",
    how: "You describe the result you want with SELECT/JOIN/WHERE/GROUP BY; the database plans and executes it, and EXPLAIN reveals whether indexes are used.",
    howZh: "你用 SELECT/JOIN/WHERE/GROUP BY 描述想要的结果；数据库规划并执行它，EXPLAIN 揭示是否用到索引。",
    resourceIds: ["fcc-db", "postgres-tutorial"],
  },
  postgres: {
    what: "PostgreSQL is a robust relational database that stores data with constraints, indexes, transactions, and rich types.",
    whatZh: "PostgreSQL 是一个健壮的关系数据库，用约束、索引、事务和丰富类型来存储数据。",
    why: "A strong, general-purpose database handles most storage needs well, so reaching for specialized stores too early usually adds complexity without payoff.",
    whyZh: "一个强大的通用数据库能很好地满足多数存储需求，所以过早引入专用存储通常只增加复杂度而无收益。",
    how: "You define tables with constraints and indexes shaped by real access patterns, and use transactions so related writes commit atomically or not at all.",
    howZh: "你依据真实访问模式定义带约束和索引的表，并用事务让相关写入要么原子提交、要么全不提交。",
    resourceIds: ["postgres-tutorial", "postgres-ddl"],
  },
  "data-modeling": {
    what: "Data modeling turns domain facts and relationships into durable structures — entities, keys, and their invariants.",
    whatZh: "数据建模把领域事实和关系变成持久结构——实体、键及其不变量。",
    why: "A poor model makes invalid states representable and pushes complexity into every query; a good one encodes the rules in the schema itself.",
    whyZh: "糟糕的模型让非法状态可被表示，并把复杂度推给每条查询；好的模型把规则编码进 Schema 本身。",
    how: "You name entities, define their identities, relationships, ownership, and lifecycle, and choose structures that match expected query patterns rather than one loose blob.",
    howZh: "你命名实体，定义它们的身份、关系、所有权和生命周期，并选择匹配预期查询模式的结构，而不是一个松散的 Blob。",
    resourceIds: ["postgres-ddl", "cosmic-python"],
  },
  migrations: {
    what: "Migrations are versioned, ordered changes to a database's schema and data applied over time.",
    whatZh: "Migration 是随时间施加的、版本化且有序的数据库 Schema 与数据变更。",
    why: "Production data cannot be dropped and recreated when types change, so schema evolution must be incremental, reversible, and safe under live traffic.",
    whyZh: "生产数据不能在类型变化时被删除重建，所以 Schema 演进必须是增量、可逆且在在线流量下安全的。",
    how: "Using expand/contract, you add new nullable structures first, backfill and deploy readers, switch writers over, then remove the old shape in a later step.",
    howZh: "用 expand/contract 方式，你先加入可空的新结构，回填并部署 Reader，再切换 Writer，最后在后续步骤移除旧结构。",
    resourceIds: ["alembic", "postgres-ddl"],
  },
  redis: {
    what: "Redis is an in-memory data store used to cache frequently read or ephemeral data close to compute.",
    whatZh: "Redis 是一个内存数据存储，用于把高频读取或临时数据缓存在贴近计算之处。",
    why: "Caching trades freshness for latency, and the hard part is not storing data but deciding when to invalidate it and what to do when the cache is unavailable.",
    whyZh: "缓存用新鲜度换延迟，难点不在存储数据，而在决定何时失效、以及缓存不可用时怎么办。",
    how: "You store values under keys with a TTL, read from the cache first and fall back to the database on a miss, invalidate on writes, and guard against stampedes.",
    howZh: "你把值按键存储并设 TTL，先读缓存、未命中时回退数据库，写入时失效，并防止缓存击穿。",
    resourceIds: ["redis", "sre-book"],
  },
  search: {
    what: "Search and vector retrieval find data by text relevance or semantic similarity rather than exact key lookups.",
    whatZh: "搜索与向量检索按文本相关性或语义相似度查找数据，而非精确键查找。",
    why: "It is a distinct access pattern from ordinary queries, and vector similarity only pays off when meaning, not exact wording, is what matters.",
    whyZh: "它是不同于普通查询的访问模式，而向量相似度只有在语义（而非精确措辞）重要时才值得。",
    how: "Full-text search tokenizes and ranks documents by keyword match; vector search embeds text into vectors and retrieves nearest neighbors by distance.",
    howZh: "全文搜索对文档分词并按关键词匹配排序；向量搜索把文本嵌入成向量，并按距离检索最近邻。",
    resourceIds: ["postgres-search", "pgvector"],
  },
  "object-storage": {
    what: "Object storage holds large immutable blobs — files, images, model artifacts — addressed by a key.",
    whatZh: "对象存储保存大型不可变 Blob——文件、图片、模型产物——通过键寻址。",
    why: "Databases are poor at storing large byte streams; keeping blobs elsewhere and only their metadata in the database keeps queries and backups lean.",
    whyZh: "数据库不擅长存储大字节流；把 Blob 放在别处、数据库只存元数据，能让查询和备份保持精简。",
    how: "You store metadata and an object key in the database, and clients upload or download the blob directly to storage through a short-lived signed URL.",
    howZh: "你在数据库存元数据和对象键，客户端通过短期签名 URL 直接向存储上传或下载 Blob。",
    resourceIds: ["s3", "owasp"],
  },
  processes: {
    what: "A process is a running program the OS manages, with a PID, memory, open files, ports, signals, and a lifecycle.",
    whatZh: "进程是操作系统管理的运行中程序，拥有 PID、内存、打开的文件、端口、信号和生命周期。",
    why: "Production software is ultimately a process that starts, consumes bounded resources, can fail, and must shut down cleanly under signals.",
    whyZh: "生产软件本质上是一个会启动、消耗有限资源、可能失败、并必须在信号下干净关闭的进程。",
    how: "The OS gives each process isolated memory and resource limits; the program handles signals like SIGTERM to drain work and exit gracefully within a deadline.",
    howZh: "操作系统给每个进程隔离的内存和资源上限；程序处理 SIGTERM 等信号以排空工作，并在期限内优雅退出。",
    resourceIds: ["linux-process", "node-learn"],
  },
  networking: {
    what: "Networking moves data between machines through sockets, TCP/IP, routing, and name resolution.",
    whatZh: "网络通过 Socket、TCP/IP、路由和域名解析在机器之间传输数据。",
    why: "Latency, timeouts, connection limits, and packet loss all surface as application behavior, so one 'slow' number hides many distinct stages.",
    whyZh: "延迟、超时、连接上限和丢包都会表现为应用行为，所以一个「慢」的数字掩盖了许多不同阶段。",
    how: "A connection is established over TCP (after DNS and often TLS), data is sent as packets routed across networks, and each stage adds its own share of latency.",
    howZh: "连接经 TCP 建立（在 DNS、通常还有 TLS 之后），数据以数据包形式跨网络路由，每个阶段各自增加一部分延迟。",
    resourceIds: ["networking-guide", "mdn-http"],
  },
  "load-balancing": {
    what: "Load balancing distributes incoming traffic across multiple healthy instances of a service.",
    whatZh: "负载均衡把进入的流量分发到一个服务的多个健康实例。",
    why: "Horizontal scale and availability require spreading load and removing failed instances without dropping requests.",
    whyZh: "水平扩展和可用性要求分散负载并在不丢弃请求的前提下摘除故障实例。",
    how: "A balancer checks instance health, routes each request by an algorithm like round-robin or least-connections, and drains connections before removing an instance.",
    howZh: "均衡器检查实例健康，用轮询、最少连接等算法路由每个请求，并在摘除实例前排空连接。",
    resourceIds: ["nginx-balancing", "sre-book"],
  },
  containers: {
    what: "A container packages a process together with a repeatable filesystem and an isolated runtime boundary.",
    whatZh: "容器把一个进程连同可复现的文件系统和隔离的运行时边界打包在一起。",
    why: "It makes 'runs on my machine' reproducible across environments, though it packages software — it does not fix architecture or operations.",
    whyZh: "它让「在我机器上能跑」在不同环境间可复现，不过它只是打包软件——不解决架构或运维问题。",
    how: "A Dockerfile builds an image in layers with pinned dependencies; the runtime starts that image as an isolated process with defined ports and health checks.",
    howZh: "Dockerfile 分层构建带锁定依赖的镜像；运行时把该镜像作为隔离进程启动，带定义好的端口和健康检查。",
    resourceIds: ["docker", "fullstack-open"],
  },
  cicd: {
    what: "CI/CD automates verifying every change and delivering it through a repeatable pipeline.",
    whatZh: "CI/CD 自动化验证每次变更，并通过可重复的流水线交付它。",
    why: "If shipping depends on undocumented manual steps, releases are slow, error-prone, and hard to roll back.",
    whyZh: "如果交付依赖没有记录的手动步骤，发布就会缓慢、易错且难以回滚。",
    how: "On each push a pipeline installs locked dependencies, runs typecheck and tests, builds artifacts, deploys, verifies health, and can roll back a bad release.",
    howZh: "每次 Push 时，流水线安装锁定依赖、运行 Typecheck 和测试、构建产物、部署、验证健康，并能回滚有问题的发布。",
    resourceIds: ["github-actions", "fullstack-open"],
  },
  observability: {
    what: "Observability uses logs, metrics, and traces to explain what a running system is actually doing.",
    whatZh: "可观测性用日志、指标和 Trace 来解释一个运行中系统实际在做什么。",
    why: "You cannot debug behavior you cannot see, and disconnected signals make it hard to trace a user problem back to its cause.",
    whyZh: "你无法调试看不见的行为，而彼此割裂的信号让人难以把用户问题追回到根因。",
    how: "Requests carry a shared ID so a log line, a trace span, and a metric all link to the same operation, and alerts fire on service-level indicators.",
    howZh: "请求携带共享 ID，让一条日志、一个 Trace Span 和一个指标都关联到同一次操作，告警则基于服务级指标触发。",
    resourceIds: ["otel", "sre-book"],
  },
  security: {
    what: "Security is controlling trust, data exposure, supply chain, and abuse paths across every boundary of a system.",
    whatZh: "安全是在系统的每个边界上控制信任、数据暴露、供应链和滥用路径。",
    why: "Vulnerabilities live at boundaries, so security is a property built into each one, not a feature added at the end.",
    whyZh: "漏洞存在于边界，所以安全是构建进每个边界的属性，而不是最后添加的功能。",
    how: "You threat-model the flow of input and identity, validate and authorize at each boundary, protect secrets, scan dependencies, and limit blast radius.",
    howZh: "你对输入和身份的流动做威胁建模，在每个边界验证与授权，保护 Secret，扫描依赖，并限制影响范围。",
    resourceIds: ["owasp", "nist-ai-rmf"],
  },
  replication: {
    what: "Replication keeps multiple copies of data across machines for availability and read capacity.",
    whatZh: "复制在多台机器上保留数据的多个副本，以提供可用性和读能力。",
    why: "Copies survive machine failure and serve more reads, but they introduce lag, failover, and choices about which value clients may read.",
    whyZh: "副本能在机器故障时存活并服务更多读取，但它们引入延迟、Failover，以及客户端可读到哪个值的选择。",
    how: "A leader accepts writes and streams them to followers; reads can be served by replicas, and on leader failure a follower is promoted, possibly losing recent writes.",
    howZh: "Leader 接受写入并把它们流式复制到 Follower；读取可由副本服务，Leader 故障时某个 Follower 被提升，可能丢失最近的写入。",
    resourceIds: ["ddia", "mit-distributed"],
  },
  partitioning: {
    what: "Partitioning splits data or work across machines by a chosen key so no single node holds everything.",
    whatZh: "分区按选定的键把数据或工作切分到多台机器，使没有单个节点承载全部。",
    why: "The partition key decides load distribution, so a bad choice creates hotspots, expensive cross-partition queries, and painful rebalancing.",
    whyZh: "分区键决定负载分布，所以错误的选择会造成热点、昂贵的跨分区查询和痛苦的重平衡。",
    how: "A key like user_id maps each record to a partition; queries within one key stay cheap, while skewed keys create hot partitions needing a different scheme.",
    howZh: "像 user_id 这样的键把每条记录映射到一个分区；单键内的查询保持低成本，而倾斜的键会造成需要另一种方案的热分区。",
    resourceIds: ["ddia", "postgres-ddl"],
  },
  consistency: {
    what: "Consistency defines which values concurrent clients are allowed to observe across replicas.",
    whatZh: "一致性定义并发客户端在多个副本间被允许观察到哪些值。",
    why: "Vague terms like 'eventual' or 'strong' must become explicit, user-visible guarantees, or behavior under concurrency becomes unpredictable.",
    whyZh: "「最终」「强」这类模糊说法必须变成显式的、用户可见的保证，否则并发下的行为将无法预测。",
    how: "Models range from strong (everyone sees the latest write) to eventual (replicas converge over time), with read-your-writes and causal guarantees in between.",
    howZh: "一致性模型从强（人人都看到最新写入）到最终（副本随时间收敛），中间还有 read-your-writes 和因果一致等保证。",
    resourceIds: ["ddia", "mit-distributed"],
  },
  consensus: {
    what: "Consensus lets a group of nodes agree on a single ordered history despite failures.",
    whatZh: "共识让一组节点在故障下就单一的有序历史达成一致。",
    why: "Reliable coordination — leader election, replicated logs — depends on agreement that survives crashes and network splits.",
    whyZh: "可靠的协调——领导选举、复制日志——依赖能在崩溃和网络分区下存活的一致。",
    how: "In Raft, nodes elect a leader per term; a write commits only once a quorum has stored it, which prevents two leaders from committing conflicting histories.",
    howZh: "在 Raft 中，节点按任期选出 Leader；写入只有在 Quorum 存储后才提交，这防止两个 Leader 提交冲突的历史。",
    resourceIds: ["mit-distributed", "ddia"],
  },
  transactions: {
    what: "A transaction groups multiple changes under atomicity and isolation guarantees so they succeed or fail as a unit.",
    whatZh: "事务把多个变更纳入原子性和隔离保证之下，使它们作为一个整体成功或失败。",
    why: "Related writes must not be left half-applied, and local versus distributed workflows need different correctness and recovery strategies.",
    whyZh: "相关的写入不能被半途应用，而本地与分布式工作流需要不同的正确性和恢复策略。",
    how: "A database commits grouped writes atomically; work that spans systems uses patterns like an outbox, a saga, or two-phase commit instead.",
    howZh: "数据库把成组的写入原子提交；跨系统的工作则改用 Outbox、Saga 或两阶段提交等模式。",
    resourceIds: ["postgres-tutorial", "ddia"],
  },
  queues: {
    what: "Queues and streams buffer work and record ordered events between producers and consumers.",
    whatZh: "队列与流在生产者和消费者之间缓冲工作并记录有序事件。",
    why: "They decouple producers from consumers and absorb bursts, but real delivery guarantees come from acknowledgements, idempotency, ordering, and replay.",
    whyZh: "它们解耦生产者和消费者并吸收突发，但真正的投递保证来自确认、幂等、顺序和重放。",
    how: "Producers append events to a topic; consumer groups share the work, track offsets to replay, and consumers stay idempotent to tolerate duplicate delivery.",
    howZh: "生产者把事件追加到 Topic；Consumer Group 分担工作，用 Offset 记录以便重放，消费者保持幂等以容忍重复投递。",
    resourceIds: ["kafka", "ddia"],
  },
  "fault-tolerance": {
    what: "Fault tolerance is keeping a system useful during timeouts, overload, and partial component failure.",
    whatZh: "容错是在超时、过载和部分组件故障时让系统保持可用。",
    why: "Failures are inevitable and naive retries can amplify them, so recovery must be designed and tested rather than assumed.",
    whyZh: "故障不可避免，而幼稚的重试会放大故障，所以恢复必须被设计和测试，而不是假定。",
    how: "You bound timeouts, retry with backoff and a budget, trip circuit breakers on repeated failure, and degrade to a reduced but working mode.",
    howZh: "你为超时设上限，用退避和预算重试，在反复失败时触发熔断，并降级到功能受限但可用的模式。",
    resourceIds: ["sre-book", "mit-distributed"],
  },
  "model-api": {
    what: "A model API turns a prompt and context into generated text, a structured decision, or a tool request.",
    whatZh: "Model API 把提示和上下文变成生成文本、结构化决策或工具请求。",
    why: "The model is probabilistic compute — powerful but not a database, permission system, or workflow engine — so it must be called with clear bounds.",
    whyZh: "模型是概率计算——强大但不是数据库、权限系统或工作流引擎——所以调用它必须有明确边界。",
    how: "You send instructions, context, and available tools with a timeout; the model streams back text or returns a structured request you then handle.",
    howZh: "你带超时地发送指令、上下文和可用工具；模型流式返回文本，或返回一个你随后处理的结构化请求。",
    resourceIds: ["model-api", "effective-agents"],
  },
  "context-window": {
    what: "Context design chooses what instructions, state, examples, and retrieved evidence go into each model call.",
    whatZh: "上下文设计选择每次模型调用放入哪些指令、状态、示例和检索到的证据。",
    why: "A model only knows what is in its context, so agent quality is often a context-architecture problem before it is a model problem.",
    whyZh: "模型只知道其上下文中的内容，所以 Agent 质量往往先是上下文架构问题，之后才是模型问题。",
    how: "You assemble stable system instructions, the current task state, only the relevant retrieved excerpts, tool definitions, and a trimmed history — not everything.",
    howZh: "你组装稳定的系统指令、当前任务状态、仅相关的检索片段、工具定义和裁剪过的历史——而不是全部。",
    resourceIds: ["effective-agents", "model-api"],
  },
  "structured-output": {
    what: "Structured output constrains a model's response to a validated, machine-readable schema.",
    whatZh: "结构化输出把模型的响应约束为经过验证、机器可读的 Schema。",
    why: "Software needs decisions it can parse reliably with explicit failure paths, not hopeful string parsing of free text.",
    whyZh: "软件需要能可靠解析、带显式失败路径的决策，而不是对自由文本碰运气地解析字符串。",
    how: "You define a schema such as JSON with required fields, instruct or constrain the model to match it, and validate — rejecting or repairing invalid responses.",
    howZh: "你定义一个 Schema（如带必填字段的 JSON），指示或约束模型匹配它，并进行验证——拒绝或修复非法响应。",
    resourceIds: ["structured-outputs", "openapi"],
  },
  "tool-use": {
    what: "Tool use lets a model request deterministic reads and actions from software instead of only producing text.",
    whatZh: "工具使用让模型向软件请求确定性的读取和操作，而不只是生成文本。",
    why: "Tools connect a model's reasoning to real state and side effects, and the schema and result design of each tool determine reliability.",
    whyZh: "工具把模型的推理连接到真实状态和副作用，而每个工具的 Schema 和结果设计决定可靠性。",
    how: "The model emits a structured call like read_file({path}); deterministic code validates arguments, checks permission, runs it, and returns a bounded result.",
    howZh: "模型发出像 read_file({path}) 这样的结构化调用；确定性代码验证参数、检查权限、执行它，并返回有界结果。",
    resourceIds: ["function-calling", "mcp-docs"],
  },
  "agent-loop": {
    what: "An agent loop repeatedly observes, decides, acts, and inspects results until a goal or stop condition is reached.",
    whatZh: "Agent Loop 反复观察、决策、行动并检查结果，直到达成目标或触发停止条件。",
    why: "The loop, its iteration limits, and its recovery logic — not the prompt alone — are what actually make an agent work.",
    whyZh: "循环、它的迭代上限和恢复逻辑——而不仅是 Prompt——才是让 Agent 真正工作的东西。",
    how: "Each turn the model picks a tool, the result is fed back, and the loop continues within an iteration budget, stopping on success, failure, or cancellation.",
    howZh: "每一轮模型选择一个工具，结果被反馈回去，循环在迭代预算内继续，并在成功、失败或取消时停止。",
    resourceIds: ["effective-agents", "pi-agent"],
  },
  memory: {
    what: "State and memory store durable user, task, and working data outside the model's transient context.",
    whatZh: "State 与 Memory 把持久的用户、任务和工作数据存储在模型的临时上下文之外。",
    why: "Conversation history is not reliable long-term memory, so durable facts need explicit ownership, lifecycle, and retrieval.",
    whyZh: "对话历史不是可靠的长期记忆，所以持久事实需要显式的所有权、生命周期和检索。",
    how: "You keep working state for the current step, session history for the conversation, and durable facts in a separate store retrieved explicitly when relevant.",
    howZh: "你为当前步骤保留工作状态，为对话保留会话历史，把持久事实存入独立 Store 并在相关时显式检索。",
    resourceIds: ["effective-agents", "mcp-docs"],
  },
  mcp: {
    what: "MCP is a protocol that standardizes how AI clients discover and invoke external tools and resources.",
    whatZh: "MCP 是一个协议，标准化 AI 客户端发现和调用外部工具与资源的方式。",
    why: "It replaces bespoke per-integration glue with a common interface, though it still needs trust, lifecycle, and permission design.",
    whyZh: "它用统一接口取代每个集成的定制胶水代码，不过仍需信任、生命周期和权限设计。",
    how: "A client starts an MCP server, discovers its tools and their JSON schemas, invokes them over a transport, and receives typed results.",
    howZh: "客户端启动一个 MCP Server，发现它的工具及其 JSON Schema，通过传输调用它们，并接收类型化结果。",
    resourceIds: ["mcp-docs", "function-calling"],
  },
  permissions: {
    what: "Permissions and human-in-the-loop constrain an agent's authority and route consequential decisions to a person.",
    whatZh: "权限与人类在环约束 Agent 的权限，并把有后果的决策交给人。",
    why: "A useful agent needs real power, but a safe one needs explicit scope and confirmation boundaries so it cannot act beyond intent.",
    whyZh: "有用的 Agent 需要真实权力，但安全的 Agent 需要显式范围和确认边界，使其无法越出意图行动。",
    how: "Operations are classified — reads allowed, reversible writes previewed, consequential actions requiring confirmation, destructive ones forbidden — and enforced.",
    howZh: "操作被分类——读取允许、可逆写入先预览、有后果的操作需确认、破坏性操作禁止——并被强制执行。",
    resourceIds: ["nist-ai-rmf", "owasp"],
  },
  evals: {
    what: "Evals and tracing measure an agent's outcomes and record the path it took to produce them.",
    whatZh: "Evals 与 Tracing 衡量 Agent 的结果，并记录它得出结果所走的路径。",
    why: "Prompt and tool changes are software changes; without evaluation they cause invisible regressions no one notices until production.",
    whyZh: "Prompt 和工具的改动就是软件改动；没有评估，它们会造成没人察觉、直到生产才暴露的回归。",
    how: "You build a task set with a success rubric, run the agent, score whether it chose the right actions and respected limits, and gate changes on the result.",
    howZh: "你构建带成功评分标准的任务集，运行 Agent，评估它是否选对操作并遵守限制，并以结果作为改动的门禁。",
    resourceIds: ["evals", "otel"],
  },
  "pi-agent": {
    what: "Pi is a small coding-agent runtime combining model providers, sessions, skills, tools, files, and a bounded loop.",
    whatZh: "Pi 是一个小型编码 Agent 运行时，组合了模型 Provider、Session、Skill、Tool、文件和有界循环。",
    why: "It is a concrete, readable reference for how a composable agent and its web workspace actually fit together.",
    whyZh: "它是一个具体、可读的参考，展示可组合的 Agent 及其 Web 工作区实际如何拼装在一起。",
    how: "A message enters a session, a model is selected, coding tools run and record file changes, and the result streams back to the workspace.",
    howZh: "消息进入会话，选定模型，编码工具运行并记录文件变化，结果流式返回工作区。",
    resourceIds: ["pi-web", "pi-agent"],
  },
  "ai-native-ux": {
    what: "AI-native UX designs software around goals, previews, collaboration, and inspectable agent work rather than a bare chat box.",
    whatZh: "AI 原生 UX 围绕目标、预览、协作和可检查的 Agent 工作来设计软件，而不是一个空白聊天框。",
    why: "Adding a chat box is not AI-native; users need control, visible progress, provenance, and a way to undo what the agent did.",
    whyZh: "加一个聊天框不等于 AI 原生；用户需要控制、可见进度、来源，以及撤销 Agent 所做之事的途径。",
    how: "The interface shows a goal, a proposed plan, live steps, a diff preview, a scoped approval boundary, an undo path, and evidence of completion.",
    howZh: "界面展示目标、提议的计划、实时步骤、Diff 预览、有范围的审批边界、撤销路径和完成证据。",
    resourceIds: ["openwork", "openworker", "effective-agents"],
  },
};
